### ISSUE TITLE
Accent Encoding, key Tag Issues

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GRA#1]
https://github.com/sanskrit-lexicon/MWS/issues/12 continued.

Now when I want to extract unique words with accents, several issues come to my attention:

1) some <key2_> have "," after them, some - none. Could not find the difference in book.
vahni,
vahman
vahya
vahye-Saya,
vA,
aBi

Only cases where I understand the necessity are (and even here they are not equal - skamB has a comma, skand has none attached):
skad, skand
skaB, skamB,
tvota, tuota, tuA-Uta,

2) other <key2_> have ")," after them, some - none. Could not find the difference in book. If key2 is based on b, then I can understand , because "<key2_>svojas), su-ojas,</key2_><_/h><_body>(<b_>svo4jas), su-o4jas,<_/b_>"
somin,
somya),
sOkftya,
sODanvana,
sOBaga,
sOBagatva,
sOBAgya,
sOmanasa,
sOmya),
sOvaSvya),
3) in other dictionaries <key2_> has the accents, here <key2_> is rather useless, because only <b_> holds what we are looking for. All I wonder is if there is more than one <b_> per entry. Sample:
<_key1_>hiraRyakeSya<_/key1_><_key2_>hiraRya-keSya),<_/key2_><_/h_><_body_>(<b_>hi4ran2ya-keçya),</b>

4) I see that yes, there are more than the accented b tag, so we have upasargas bolded as well. The only way around is to search and replace them, I guess:
hva1ra4,
hva1rya4),
hvr3, hru,
- a10
- u4pa
- pa4ri
- vi4

hruta

<b>Q.</b>: Please advice, how can I extract the first <b>b</b> in each entry? That way I will have all accents I'm hunting for.

**Comment by drdhaval2785** [comment]
Looking at gra.txt as it stands today,
the entry hiraRyakeSya is as follows
```
<L>10666<pc>1666<k1>hiraRyakeSya<k2>hi/raRya-keSya
({@híraṇya-keśya@})¦, {@híraṇya-keśia,@} a., {%goldmähnig.%} <lbinfo n="9"/>
<div n="P1">-ā hárī 652,29; 702,24.
<LEND>
```
Therefore, the accent has moved to k2. Therefore, the issue raised by @gasyoun does not survive now. Closing.
