### ISSUE TITLE
Space after comma missing

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GRA#10]
`pinv,1) schwellen` -> `pinv, 1) schwellen` @funderburkjim

**Comment by gasyoun** [comment]
@funderburkjim does it sound like a quick fix?

**Comment by Andhrabharati** [comment]
@gasyoun 

My present re-worked file has taken care of this point, and as Jim is going to 'consider' using my new file for the next CDSL version, this issue can be closed now.
