### ISSUE TITLE
pate 570,1—3

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GRA#15]
Not only 1 should be linked, but interval until 3 us well. Regex did not catch it, @funderburkjim 

![vastu](https://user-images.githubusercontent.com/80761/108475060-44880c80-72a1-11eb-9acc-e5033bd9c7c5.JPG)

**Comment by funderburkjim** [comment]
In this case, I don't see any real problem -- if the user clicks the link to 570,1  then verses
2 and 3 will be visible.

**Comment by gasyoun** [comment]
> if the user clicks the link to 570,1 then verses 2 and 3 will be visible.

Sure he will, but the 3 is bigger than 1, but should be same size font.

**Comment by funderburkjim** [comment]
In the scans, the '1' is NOT smaller.   All the digits are same size

![image](https://user-images.githubusercontent.com/6393033/113602525-b9749300-9610-11eb-8d1f-5d1a59727650.png)

So there should be TWO adjustments:
1. include the '3' in the link (`570,1—3` all underlined)
2. Have all digits the same size  (the '1' not smaller).

@gasyoun Agree?

**Comment by funderburkjim** [comment]
You also noticed a case where a rare AV reference was wrongly treated as a RV reference.

Which issue is this?

**Comment by gasyoun** [comment]
> In the scans, the '1' is NOT smaller. All the digits are same size

Same size in print, not in our digitization.  

> So there should be TWO adjustments

Agree.

**Comment by funderburkjim** [comment]
@gasyoun  I found the AV issue -- it is #3.

**Comment by gasyoun** [comment]
> it is #3.

Oh yes it is.

**Comment by funderburkjim** [comment]
Have added markup to gra.txt for the RV references. Examples
* {494,1}; 
* vāstos {570,1—3}
* {798,2. 4. 17}

Altered display code to handle this markup: [basicadjust.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc/basicadjust.php)

Also,  Unmarked the AV references, so they won't be erroneously linked to RV (#3)

Also, greatly reduced the unlinked RV references, and extended the scope of the link text (#5).

![image](https://user-images.githubusercontent.com/6393033/113796838-1f027580-971e-11eb-866d-95d6d1521a32.png)

![image](https://user-images.githubusercontent.com/6393033/113796971-5cff9980-971e-11eb-8b44-d33f6155bb6b.png)

**Comment by funderburkjim** [comment]
## Tech doc
Here are the required files to do the revision to gra.txt.  They are run in a temp_ls subdirectory
of csl-orig/v02/gra/.

The files are in [this gist](https://gist.github.com/funderburkjim/dfff1108ef3dc5702cb3412d06f75b96).

The files briefly described:
*  readme.txt repeatable instructions
* rvmarkup.py  program applies markup to {xxx,x} and similar instances.  This gets most, but
   not all markup.
* avmarkup.py  Remove the {xxx,x} markup for AV links
* filter1.py  Search for a few anomalous cases and generate prototype change transactions
* filter1_edit.txt  Manually corrected change transactions based on output of filter1.py.
   Also, a few additional changes noticed along the way
* rvmarkup1.py  {xxx,x} markup occurring at beginning or end of lines.  (These were missed
   by rvmarkup

**Comment by funderburkjim** [comment]
Further work that could be done.

Currently, the xml form (gra.xml) contains {xxx,x} markup.  

The conversion of these links to the 'modern' links is done on the fly by basicadjust.php.

It might be better to
* do the conversion to modern links in make_xml.py .  
  For example, instead of {570,1}  in gra.xml, we might have `<ls n="rv07.054.01">570,1</ls>`
* and then basicadjust would be much simpler by  using this `rv07.054.01` attribute value.

This change would
* make the display program less complex
* make gra.xml more informative
* provide a form that could more readily be extended to cover the AV links (#3)

**Comment by gasyoun** [comment]
> instead of {570,1} in gra.xml, we might have <ls n="rv07.054.01">570,1</ls>

Makes sense, but if Jim will not, nobody will. Otherwise the different `basicadjust.php` will always remain such.

**Comment by funderburkjim** [comment]
> if Jim will not, nobody will

This is a persistent problem.  There are too many potential improvements that currently depend on me for implementation.

**Comment by gasyoun** [comment]
> too many potential improvements that currently depend on me for implementation

Let's have a Skype call. I guess I have a guy, but we are a bit away of the December plan because of too much MW addenda lately ))
