### ISSUE TITLE
enthālten -> enthälten

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GRA#16]
maṅgala [Printed book page 0973]
(maṅgalá) , n., Glück, Segen (wol von einer Wurzel mañj, die in den Ableitungen die Begriffe der Schönheit, der Blüthen- oder Farbenpracht entwickelt), enthālten in ádurmaṅgala, su-maṅgála.  

![altend](https://user-images.githubusercontent.com/80761/114087315-6aeb2100-98bc-11eb-81a6-754d9df50f74.JPG)

Print error in book. `ā` is impossible in a German word.

**Comment by funderburkjim** [comment]
Should it be enthalten  ?  (no umlaut).

Reason: enthalten  occurs 644 times in GRA, but enthälten occurs 0 times.

**Comment by gasyoun** [comment]
> Should it be enthalten ? (no umlaut).

Let it be, no umlaut.

**Comment by funderburkjim** [comment]
Correction installed.

Noted as print change in [gra_printchange.txt](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/gra/gra_printchange.txt).
