### ISSUE TITLE
Grasmann annexure pages missing?

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/GRA#17]
@funderburkjim & @thomasincambodia 

I just happened to land at this for some reason.

As usual, wrt to my copy, noticed that VN pages (1741-48) and Nachtrage pages (1749-1776) are missing in the downloadable file.

And there is a Nachwort (1/2 page) at the end that could go to the csl-doc area.

**Any clue about these missings?**

[Unlike the PWG case, where the VN pages data could be traced in the earlier (2014) download file (_orig.txt), this gra.txt has no such luck!!]
`--------`
@gasyoun 

There is a "reverse" word-index in 1687-1740 pages, in between the main text and the VN pages mentioned above.
This could be of some interest for you.

**Comment by Andhrabharati** [comment]
Also there is a similar work on Samaveda, Glossar zu Samaveda by Benfey (1848), which is 210pp. long.

It is worth adding to CDSL, I would say.

**Comment by gasyoun** [comment]
> This could be of some interest for you.

Yes, I'm aware of it. I'm working on my own. On Grassman's reverse index a dissertation was based:
https://yadi.sk/i/q8OihOnLjyKmbQ [Lubotsky_A.M.]_The_system_of_nominal_accentuation

![1322](https://user-images.githubusercontent.com/80761/132106406-7e40c274-c081-45b3-9599-c591af501075.png)

**Comment by Andhrabharati** [comment]
> It's based on a specific work. I'm against. 

What is Grasmann then?

**Comment by gasyoun** [comment]
> What is Grasmann then?

It is the same. But Rigveda is of more interest than Samaveda, which is a remix of Rigveda. Too much work can kill us.

**Comment by funderburkjim** [comment]
> GRA VN pages (1741-48) and Nachtrage pages (1749-1776)  are missing in the downloadable file.

@Andhrabharati 

The downloadable file you mention is csl-orig/v02/gra/gra.txt

gra.txt  goes through 'hvf'  [page 1686 (top)](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=gra&page=1685)

The scan pages from  'Verzeichnisse nach dem Endlaute' at bottom of 1686 through page 1776 are available,

and the Nachwort (Epilogue) is at bottom of [page 1776](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=gra&page=1776).

So, you are making two points, I think:
1.  Request of digitization of the pages 1686 through 1776
    * And possible additions to gra.txt from some of these pages (such as the [VN section](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=gra&page=1741)
2. Request to put the Nachwort in https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/grapref.html

Have I accurately rephrased your suggestions regarding Grassman?

**Comment by Andhrabharati** [comment]
you just said it exactly (in your way) what I meant (in my way).

**Comment by funderburkjim** [comment]
> digitizing only 1741-76, 

@thomasincambodia     These pages of Grassman need to be digitized.   Do you agree?

**Comment by Andhrabharati** [comment]
As these VN pages are now 'digitised', this issue can be closed now.
