### ISSUE TITLE
Grassman improved scans

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GRA#19]
New scans of Grassman dictionary would be desirable.
This continues the discussion begun at https://github.com/sanskrit-lexicon/SKD/issues/15#issuecomment-1350358089.

Also, #17 is related.

For convenience, I have copied the GRA comments from the skd issue above:

# @funderburkjim said:
I know there is at least one dictionary that could use better quality scans - GRA (Grassman).  A few of  sanskrit-lexicon scans for GRA have missing data (e.g. page 115), and many pages are of marginal quality and highly skewed.  It would be nice to have good quality scans for the entire dictionary.

# @Andhrabharati said:
I do have a good scan of GRA (1873) from Bayerisch Stattlib, and also a revision of the work by Maria Kozianka (1996).
This revision is similar to the revision/update of Bloomfield's Vedic Concordance; and incidentally both these revisions took place about a century later (wrt to the original editions)!

It would be a plausible option to update Cologne's GRA with this 1996 work-- @maltenth and @funderburkjim  may ponder on this suggestion.

# @gasyoun said
In relation to the 1996 work,
It will become a copyright issue.

**Comment by funderburkjim** [comment]
@Andhrabharati   Let's proceed with the Bayerisch Stattlib scans.

Once you and I get the new skd scans installed (refer: https://github.com/sanskrit-lexicon/SKD/issues/16), 
we can use a similar process to get the new gra scans installed.  We should also be able to get the 'annexure' scans installed at the same time.  (digitization of the annexure is a separate question)

**Comment by Andhrabharati** [comment]
> @Andhrabharati Let's proceed with the Bayerisch Stattlib scans.

@funderburkjim 
There is one archive.org GRA as well, that is of reasonably good quality.
Just FYI, to decide which one to use for replacing the existing CDSL scans.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Here is the link to Bayerisch Stattlib scan--
https://opacplus.bsb-muenchen.de/title/BV005081970

**Comment by funderburkjim** [comment]
Bayerisch Stattlib scans now installed at:
* Cologne -- in location used by apps csl-apidev/serveimg and displays
  * individual page url: https://sanskrit-lexicon.uni-koeln.de/scans/GRAScan/GRAScanpdf/pg_0125.pdf
* repository https://github.com/sanskrit-lexicon-scans/gra
  * previous images at https://github.com/sanskrit-lexicon-scans/gra-v0
* https://sanskrit-lexicon-scans.github.io/gra/ website, such as
  * https://sanskrit-lexicon-scans.github.io/gra/pdfpages/pg_0123.pdf
  
one obstacle to renaming the pages from Bayer is that there were many (50+) duplicate pages.  Refer: *work* directory at https://github.com/sanskrit-lexicon-scans/gra repository.

**Comment by gasyoun** [comment]
> In relation to the 1996 work, It will become a copyright issue.

But we can write a letter to ask about an errata list. It might be an open one.
