### ISSUE TITLE
GRA abbr. markup

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/GRA#27]
@funderburkjim 
In my current reworking, marked and identified almost all the occurrences, except a few (8) that need to be "deciphered".
[ab expansion pending.txt](https://github.com/sanskrit-lexicon/GRA/files/11608434/ab.expansion.pending.txt)

**Request someone to have a look at these and resolve.**
`-------------------------------------------`
Also I had separated out languages from the regular abbr. list.
[GRA lang tags with expansion.txt](https://github.com/sanskrit-lexicon/GRA/files/11608440/GRA.lang.tags.with.expansion.txt)

The Person numbers, which have a role in inflexion etc., are also separated out.
[GRA pe tags.txt](https://github.com/sanskrit-lexicon/GRA/files/11608450/GRA.pe.tags.txt)

**Comment by Andhrabharati** [comment]
Now, there are 418 entries in my ab list (incl. the 8 above mentioned), and I've marked all of them individually as `<ab n="xxx">AAA</ab>`; these can be later changed to regular local and global ab tags based on the no. occurrences (if required).

**Comment by Andhrabharati** [comment]
I have tried to expand the abbr.s in German itself; probably they could be rendered in English as well (by someone).

**Comment by Andhrabharati** [comment]
Here is the list of 292 ab entries that I've made--
[GRA ab tags.txt](https://github.com/sanskrit-lexicon/GRA/files/11608697/GRA.ab.tags.txt)

And, this has few doubtful entries that need to be checked again and confirmed--
`<ab n="concretes ??">concret.</ab>`
`<ab n="das ??">d.</ab>`
`<ab n="des ??">d.</ab>`
`<ab n="dort ??">d.</ab>`

**Comment by Andhrabharati** [comment]
Just resolved one of the 8 ab entries, by chance--
`<ab n="Priyamedha">Pr.</ab>`

**Comment by funderburkjim** [comment]
@Andhrabharati  Have requested Thomas to look at 'ab expansion pending'.  And will request his help on others, as he is able to  respond.

Another resource might be @fxru at Cologne.

**Comment by Andhrabharati** [comment]
> I feel the plural and singular do not occur simultaneously, so the `<ab>p.</ab> <ab>s.</ab>` under L-9851 (entry: suprajA)
> `<div n="TS">-ā́s [<ab n="Nominativ">N.</ab> <ab>p.</ab> <ab>s.</ab>] vayám {346,6} (siāma).`
> could be changed as 
> `<div n="TS">-ā́s [<ab n="Nominativ">N.</ab> <ab n="plural">p.</ab>] <ab n="siehe">s.</ab> vayám {346,6} (siāma).`
> 
> [There are few other places where such cf. strings **for example citations** are present in the whole text.]
> 

I considered the placement of ']' again, and decided to change [N. p. s.] as [N. p  m.] as the word under discussion is a plural masculine.

**Comment by Andhrabharati** [comment]
> And, this has few doubtful entries that need to be checked again and confirmed--
> `<ab n="concretes ??">concret.</ab>`
> `<ab n="das ??">d.</ab>`
> `<ab n="des ??">d.</ab>`
> `<ab n="dort ??">d.</ab>`

Here are the places that these are marked, for checking by someone--

**`<ab n="concretes ??">concret.</ab>`** -- 3 places

```
<L>3637<pc>0517<k1>tan<k2>ta/n
4〉 <ab n="concretes ??">concret.</ab>, die {%Nachkommenschaft,%} die {%Kinder%} (collectiv).
```

```
<L>6388<pc>0939<k1>Buj<k2>Bu/j
[Page940]
3〉 <ab n="concretes ??">concret.</ab> der {%Geniessende%}.
```

```
<L>7298<pc>1145<k1>ranti<k2>ra/nti
2〉 <ab n="concretes ??">concret.</ab> {%Erfreuer%}.
```

**`<ab n="das ??">d.</ab>`** -- 1 place

```
<L>6437<pc>0955<k1>Bf<k2>Bf
[Page957]
<div n="Pf">{@sám@} 1〉 {%zusammenziehen, zusammenlegen%} (ein Gewebe); 2〉 <ab n="medium">me.</ab> {%zusammenklappen%} (<ab n="das ??">d.</ab> Kinnbacken);
```

**`<ab n="des ??">d.</ab>`** -- 1 place
```
<L>508<pc>0057<k1>anIka<k2>a/nIka
[Page58]
<div n="TS">-am 1〉 máma (<ab n="des ??">d.</ab> Indra) {874,3}.
```

**`<ab n="dort ??">d.</ab>`** -- 1 place
```
<L>7677<pc>1214<k1>vayas<k2>2. va/yas
Verbunden mit bṛhát in den Bedeutungen 4—6; uttamá 4 und 7; revát 5—7; citrá 6 (<ab n="siehe unter">s. u.</ab> <ab n="dort ??">d.</ab>).
```

**Comment by Andhrabharati** [comment]
There is another place where a ?? is marked--
```
<L>7098<pc>1108<k1>yAtuDAna<k2>yAtu-DA/na
<div n="TS">-asya {913,??} tvácam {5}. mū́lam {10}. bálam {25}.
```

I would suggest changing this as
`<div n="TS">-asya tvácam {913,5}. mū́lam {10}. bálam {25}.`
to be in uniformity with the (single digit) padded links everywhere else.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Pl. get the above places confirmed by someone.

This would make the issue closable.

**Comment by Andhrabharati** [comment]
> <ab>Ds.</ab> ;;could it be Deutestamme?
> under L-1204 (entry: avyat)
> <div n="TS">-atyai [<ab>Ds.</ab> <ab n="femininum">f.</ab>] {921,5} me (urváśyai).

Here Ds. is a print error, and should just be D. (Dativ)
<div n="TS">-atyai [<ab n="Dativ">D.</ab> <ab n="femininum">f.</ab>] {921,5} me (urváśyai).

See under http://sanskrit.segal.net.br/en/decl?id=27742

**Comment by funderburkjim** [comment]
> `<ab n="siehe">s.</ab> `

So this is an example where the 's.' abbreviation means 'siehe - please refer', instead of the (usual) meaning of 'singular.'    Such 'abbreviation ambiguity'  probably explains why you chose to everywhere use the 'n='  form of abbreviation markup (since the 'n=' form removes ambiguity).

**Comment by Andhrabharati** [comment]
You got me right, @funderburkjim !

**Comment by Andhrabharati** [comment]
Here is the full list of such abbr.s--

```
<ab n="Accusativ">A.</ab>
<ab n="Aryama">A.</ab>

<ab n="Karañja">K.</ab>
<ab n="Kutsa">K.</ab>

<ab n="Mitra">M.</ab>
<ab n="Mātaríśva">M.</ab>

<ab n="Palasti">P.</ab>
<ab n="Participium">P.</ab>

<ab n="Variante">Var.</ab>
<ab n="Varuna">Var.</ab>

<ab n="Viśvāmitra">V.</ab>
<ab n="Vocativ">V.</ab>
<ab n="Vorige">V.</ab>

<ab n="das">d.</ab>
<ab n="der">d.</ab>
<ab n="des">d.</ab>
<ab n="dort ??">d.</ab>
<ab n="dual">d.</ab>

<ab n="femininum">f.</ab>
<ab n="folgende">f.</ab>

<ab n="masculinum">m.</ab>
<ab n="mit">m.</ab>

<ab n="nach">n.</ab>
<ab n="neutrum">n.</ab>

<ab n="siehe">s.</ab>
<ab n="singular">s.</ab>

<ab n="und">u.</ab>
<ab n="unter">u.</ab>

<ab n="vom">v.</ab>
<ab n="von">v.</ab>
<ab n="vorige">v.</ab>
```

**Comment by Andhrabharati** [comment]
From the context (of the citations), it looks like `<ab>pp.</ab>` stands for "plurals" [English] (more than two of **different** types/entities, as against the plural indicating many of the **same** type/entity).

But, what is the German equivalent of such term?

**Comment by Andhrabharati** [comment]
Looks like **ms.** indicates "manuscript" [the std. abbr. form being **Ms.**], that has the variant form shown.

**Comment by Andhrabharati** [comment]
> `<ab>Gm.</ab>` ;; appears to be some person's name (Scientific nomenclature)
> under L-3187 (entry: cakravAka)
> Anas Casarca `<ab>Gm.</ab>`

`<ab>Gm.</ab>` stands for Gmelin (Johann Friedrich Gmelin), who has published his work in 1789.

**Comment by funderburkjim** [comment]
> Pl. get the above points also confirmed by someone.

Regarding help from German language people (such as @maltenth or @fxru , maybe @gasyoun ?) for abbreviation tooltips and (perhaps other questions).

The timing is uncertain for receipt of such help .

We should proceed under the assumption that such help will NOT be available.

**Comment by fxru** [comment]
I looked through the abbreviations, and none seemed completely implausible, but without context it's very difficult to say anything definite.

pp. is used as an abbreviation for "and so forth" (see <https://en.m.wiktionary.org/wiki/etc._pp.> would that fit the context? I haven't seen it as "plurals" but I wouldn't rule it out.

In general, 19th and.early 20th century lexicographical German has some unusual abbreviations.

**Comment by funderburkjim** [comment]
@fxru  Hi!  Very timely to see your note. Maybe @Andhrabharati can work with you to resolve his questions regarding abbreviations -- This would include providing context in some form useable to you.  Maybe a copy of his current version of grassman digitization?

**Comment by fxru** [comment]
Yes, we can do that. I can make a list of more unusual abbreviations where checking in context might improve things.

(Ignoring any abbreviations of personal names or of literary works.)

And then we go from there.

**Comment by fxru** [comment]
Sounds very reasonable, I haven't seen "pp" as plurals, but that doesn't mean it doesn't exist. (I looked at the lists yesterday on my computer, but I'm currently writing on my phone, I'll take a better look later, when I'm back at my desk.)

**Comment by Andhrabharati** [comment]
Let me see if the **hzv.** could be from Latin (taking a clue from your above post reg. **pp.**).

**Comment by Andhrabharati** [comment]
> Sounds very reasonable, I haven't seen "pp" as plurals, but that doesn't mean it doesn't exist. (I looked at the lists yesterday on my computer, but I'm currently writing on my phone, I'll take a better look later, when I'm back at my desk.)

@fxru 

We know that **p.** is mostly used to abbreviate "plural" in Grassmann's dictionary; my interpretation of **pp.** as plurals is analogous to **Codd.** (Codices) vs. **Cod.** (Codice) used in the same work. The last letter in the abbr. gets repeated to indicate plurality/multiplicity.

A similar one, though not occurring in GRA, is `qq.vv.` vs. `q.v.`

**Comment by fxru** [comment]
In other German 19th century dictionaries _hzv._ is an abbreviation for _Huzvaresh_ or _huzvâresh_ (apparently an old name for Pahlavi) would that work in these contexts?

**Comment by Andhrabharati** [comment]
Yes @fxru, that fits the context perfectly; thanks for finding this out.

In my present work, it shall be taken as "Middle Persian [as termed by Mayrhofer, **mp.**	= mittelpersisch / Middle Persian].

> Middle Persian, also known as Pahlavi, was in use from about A.D. 250 to 900. It was the official language of the Sassanid Empire and of the Zoroastrian priesthood. It was written in an ideographic script called Huzvaresh.

**Comment by Andhrabharati** [comment]
> I looked through the abbreviations, and none seemed completely implausible, but without context it's very difficult to say anything definite.
> 
> pp. is used as an abbreviation for "and so forth" (see https://en.m.wiktionary.org/wiki/etc._pp. would that fit the context? I haven't seen it as "plurals" but I wouldn't rule it out.
> 
> In general, 19th and.early 20th century lexicographical German has some unusual abbreviations.

@fxru

I was very hasty in my earlier post(s) saying that the involved citations contain the full list, and nothing like **etc.** to mean the "tail-enders" & tried to hang on to my interpretation of "plurals". Though I am right so far as the citations themselves are concerned, the GRA text has only the first entity of the list, and indicated the rest by **pp.**

When I finally tried to mark the abbr.s in my file, noticed this gross error on my side; really sorry for having not listed to you carefully and go through the text before posting my responses.

**The expansion `perge, perge` is what is fitting in these places.**

**Comment by Andhrabharati** [comment]
Now, I request you to check the items at <https://github.com/sanskrit-lexicon/GRA/issues/27#issuecomment-1574658187> for which I am attaching the scan portions below--

> `<ab n="concretes ??">concret.</ab>` -- 3 places

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/4a5bdabe-fb01-4887-a17a-8139b979d671)

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/ea3bcafc-5e05-43a8-9ea7-092293892269)

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/c6c5a45d-17b8-416a-8283-32bc82b4d27e)

> `<ab n="das ??">d.</ab>` -- 1 place

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/fb374d4c-d338-491f-af78-eb3da6229fdf)

or could this be **der** here?

> `<ab n="des ??">d.</ab>` -- 1 place

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/55c5551e-deb1-47b9-a252-2158712eb2e2)

[There are 76 places in GRA having "des Indra".]

> `<ab n="dort ??">d.</ab>` -- 1 place

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/db9165b2-a31c-43b7-879b-44d9ee8047a8)

[There are 72 places in GRA having "siehe dort".]

With these resolved, my present work on GRA will be finished (to satisfaction) to hand over to @funderburkjim for further processing.

**Comment by funderburkjim** [comment]
@Andhrabharati 

@maltenth provided several comments on abbreviations:  Thanks, Thomas!
```

<ab>Ds.</ab> ;;could it be Deutestamme?
under L-1204 (entry: avyat)
<div n="TS">-atyai [<ab>Ds.</ab> <ab n="femininum">f.</ab>] {921,5} me (urvásyai).

it could be, but it is "Deutestamm" (Deutestamm*e* being the Dative Singular form)
There are 34 occurences of "Deutest*" in grassmann,  but only one abbreviated form "Ds.".
So probably "Ds." should be changed into "Deutestamm". How would that work?

------------------------------------------------------------------

<ab>Gm.</ab> ;; appears to be some person's name (Scientific nomenclature)
under L-3187 (entry: cakravAka)
Anas Casarca <ab>Gm.</ab>

"Gm." stands for "Gmelin", the editor of Linnaeus' Systema Naturae, in biological taxonomy the
abbreviation of the first to discover a species is added to to the scientific name, or something like that,
so the abbr. "Gm." (occurs once in gras) should be kept? And maybe the tooltip gives the full name?

------------------------------------------------------------------

<ab>Pr.</ab>
under L-6077 (entry: priyameDa)
<div n="TS">-avát (wie <ab>Pr.</ab>) {45,3}.

"Pr." occurs twice and stands for  "Pra1tis4." (2x)  which stands for "Pra1tis4akhya" (once), usually preceded
by "RV" for "R2gveda"

------------------------------------------------------------------

<ab>antreff.</ab>
under L-1210 (entry: 1. aS)
<div n="TS">-ávamahai 1> jivám (lebend <ab>antreff.</ab>) {923,17}.

funny abbreviation, this "antreff." (1x), should stand for "antreffen"; "lebend antreffen" means "find
[that someone is still] alive [when the speaker goes to meet him]";
shouldn't be abbreviated; maybe the meaning of "-ávamahai" can help to elucidate this matter

------------------------------------------------------------------


<ab>hzv.</ab>
under L-10215 (entry: stana)
fstana ist aus pi-stana (<ab>hzv.</ab> <ab n="und so weiter">u. s. w.</ab> pistan)

Thank you, Felix!

------------------------------------------------------------------

<ab>ms.</ab>
under L-4852 (entry: namI)
(sayiám, oder sapiám nach <ab>ms.</ab> <ls>Chambers</ls> {60})


"ms." = "manuscript" is the usual abbreviation (occurs once)
"Chambers" stands for the Sanskrit manuscript collection of Robert Chambers (1737-1803) a catalogue of which was
compiled by Friedrich Rosen, published 1837

------------------------------------------------------------------

<ab>part.</ab> <ab>n.</ab>
under L-392 (entry: an)
<ab>part.</ab> <ab>n.</ab>, {%das Beseelte%}.

part. n.   ??


------------------------------------------------------------------



<ab>p.</ab> <ab>s.</ab>
under L-9851 (entry: suprajA)
<div n="TS">-a´s [<ab n="Nominativ">N.</ab> <ab>p.</ab> <ab>s.</ab>] vayám {346,6} (siama).

N. p. s.

"N." could be "Nomen" N.p. = proper noun

------------------------------------------------------------------


<ab>pp.</ab>
under L-6408 (entry: BUmi)
(dyaús <ab>pp.</ab>)

under L-6861 (entry: mI)
mitrám <ab>pp.</ab> {915,8. 9}.

under L-9156 (entry: sajozas)
agnís <ab>pp.</ab> {891,1}; aryama´ <ab>pp.</ab> {952,1}.

```

**Comment by Andhrabharati** [comment]
> `<ab>Pr.</ab>`
> under L-6077 (entry: priyameDa)
> `<div n="TS">-avát (wie <ab>Pr.</ab>) {45,3}.`
> 
> "Pr." occurs twice and stands for  "Pra1tis4." (2x)  which stands for "Pra1tis4akhya" (once), usually preceded
> by "RV" for "R2gveda"

Whereever Rigveda-Prātiśākhya is meant, it has the citation position invariably in GRA--
`<ls>RV. Prātiś.</ls> {255. 371}`; `<ls>RV. Prātiś. M. M.</ls> {s. 465}` and `<ls>RV. Pr.</ls> {104,16}`

Now coming to my interpretation of `<ab>Pr.</ab>`, there are 3 places where `wie <ab>xxx</ab>` is present--

`<div n="TS">-avát (wie <ab n="Priyamedha">Pr.</ab>) {45,3}.` under `<L>6077<pc>0891<k1>priyameDa<k2>priya/-meDa`

[Geld. Tr.] Wie von Priyamedha, wie von Atri, von Virupa, o Jatavedas, wie von Angiras, so erhöre den Ruf des Praskanva, du Hochgebietender!

<div n="TS">-avát wie <ab n="Bharadvāja">Bharadv.</ab> {506,6}. under <L>6317<pc>0928<k1>BaradvAja<k2>Bara/d-vAja

**Comment by fxru** [comment]
> concret.

I read that as _concretum_ (so _nomen concretum_ as opposed to _nomen abstractum_).

> or could this be **der** here?

Yes, genitive _der Kinnbacken_ is correct and the most natural. (Kinnbacken are the side part of the chin covering the submental glands ... I'm not sure what collapsing of that part of the face could mean, but that's what it says.

> [There are 76 places in GRA having "des Indra".]

I would read the same here, but a little larger snippet of the entry might make things clearer

> s. u. d.

I'm not sure what _s. u. d._ could mean _s. u._ "siehe unten" ("see below") is very common, "siehe dort" ist also not unusual, but I have never seen _s. u. d._ nor could I find any instance of _s. u. d._ in other works.

**Comment by fxru** [comment]
> <ab>part.</ab> <ab>n.</ab>
> under L-392 (entry: an)
> <ab>part.</ab> <ab>n.</ab>, {%das Beseelte%}.

Maybe _participium_ (or _Partizip_) and _neutrum_? It would fit _das Beseelte_ which is the neuter form of the participle _besselt_ (here used as a noun).

**Comment by Andhrabharati** [comment]
Great help, @fxru!

Now that all my queries are answered, I can have a peaceful sleep tonight!!

**Comment by fxru** [comment]
Thanks for the very helpful presentation of the abbreviations with snippets of scans and everything!

**Comment by Andhrabharati** [comment]
> Now, there are 292 entries in my ab list (excl. the 8 above mentioned), and I've marked all of them individually as `<ab n="xxx">AAA</ab>`; these can be later changed to regular local and global ab tags based on the no. occurrences (if required).

At the end, the abbr. count in my file is now 299.

Here are the counts of abbr.s having different expansions [very smaller counts are ignored!]--

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/f62eae40-b0db-4e0e-8aac-926aaac50588)

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/18a78edb-e9c9-4ae0-bad2-b5368353a8a2)

@funderburkjim may decide whether to retain the expansions completely as I did, or make the larger count abbr.s as global and the rest as the local abbr.s when he takes up my file; and **with this my work on GRA is over for now.**

**Comment by Andhrabharati** [comment]
> "ms." = "manuscript" is the usual abbreviation (occurs once)
> "Chambers" stands for the Sanskrit manuscript collection of Robert Chambers (1737-1803) a catalogue of which was
> compiled by Friedrich Rosen, published 1837

Let us first make a note of "**CHAMBERS, Sir ROBERT (1737–1803), Indian judge**" vs. "**CHAMBERS, ROBERT (1802–1871), Edinburgh publisher**" in the Dictionary of National Biography.

Now coming to Rosen's catalogue--

Friedrich August Rosen did indeed prepare a catalogue of the Chambers collection in 1832,
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/73559e8a-7baf-43db-a1c6-0d210411a030)

that got printed in 1838 in London;
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/41d6d7b8-a434-4aee-a158-e59c863d5bb9)

but this appears to be not "properly" organised/done. See what this has for the works referred in GRA as Chambers 60 and 61.
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/06e4845b-9574-49ef-b901-bf7125cfb9a3)

The catalogue is later thoroughly revised (or probably prepared afresh) by someone else ("D. F.") in 1841,
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/de12bdec-4a9b-4d02-b714-a31949f88e61)

as a notice for an auction of the collection in  London by the Lady Chambers (in 1842)
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/2eec51fc-2689-4e08-ae34-5ae53ea63a2b)

that contained the **popular** references to the collection's titles.
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/92580c34-025d-48fb-8d0b-7439d0cfd191)

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/3b80bf7d-69c5-4468-8c78-3369086c0006)

However, it is the Weber's catalogue that made the contents of the works fully presented to the scholars world-over.
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/a82f04e9-8271-47ac-b3cc-4b80ca13a61f)

[And it is not out of context, to mention that Weber's Descriptive catalogue made itself a standard 'style' once it got published, providing/highlighting all the useful and necessary details.]

Thus, we can see that the Lady Chambers' auction at London got purchased by the Royal Library of Berlin.

Grassmann says thus, in his Worterbuch--
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/c61e779d-3c3f-4841-a971-fc658a090497)


**acknowledging the Royal Library, Berlin.**

**Comment by Andhrabharati** [comment]
> but I have never seen _s. u. d._ nor could I find any instance of _s. u. d._ in other works.

@fxru 

Just like to mention to you that PWG has **s. u. d.** at 52 places, followed by W. (Wort/Word) or Ww. (Worten/Words).

Here are the first ones (of each type) in the PWG set--

[PWG1-0130]
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/0c35e2a1-020c-4223-aa3b-ff84cdead543)

[PWG1-0401]
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/4d30abfe-a669-4d71-a1cb-86d3989061d5)

Any thoughts now, about resolving the "dort ??", as my initial guess?

**Comment by fxru** [comment]
Ah, that changes the whole thing! Then it's in all likelihood :

s.u.d.W. -> _siehe unter diesem Wort_

s.u.d.Ww. -> _siehe unter diesen Wörtern_

So _see this/that entry_

**Comment by Andhrabharati** [comment]
Wonderful!

**Comment by Andhrabharati** [comment]
@funderburkjim, pl. make a note of this.

**Comment by Andhrabharati** [comment]
The new catalogue of Chambers collection was prepared by Dr. Forbes [**D. F.**]--

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/350a2e5a-5fb5-4937-b913-bd00600c35d1)

**Comment by funderburkjim** [comment]
> pl. make a note of this; in GRA's context, the plural form "siehe unter diesen/see under those" is applicable.

@Andhrabharati   Are there instances in GRA of s.u.d.W. and/or s.u.d.W.w ?

**Comment by Andhrabharati** [comment]
No; this is reg. the "dort ??" expansion, under L-7677.

`<ab n="siehe unter">s. u.</ab> <ab n="dort ??">d.</ab>` is to be replaced as 
`<ab n="siehe unter diesen">s. u. d.</ab>`

**Comment by Andhrabharati** [comment]
@funderburkjim 

Just noted this in PTS Pali-English Dictionary--
**∼** and **≈** means "at similar" or "at identical, parallel passages"

This expansion could be adopted in GRA also, for ⁓ [U+2053] which is used (twice) exactly for the same purpose.
**But how and where, as an abbr. or …?**

[Ref. the [earlier issue](https://github.com/sanskrit-lexicon/csl-orig/issues/609#issue-988860544]) reg. the same point.]

**Comment by Andhrabharati** [comment]
> Ah, that changes the whole thing! Then it's in all likelihood :
> 
> s.u.d.W. -> _siehe unter diesem Wort_
> 
> s.u.d.Ww. -> _siehe unter diesen Wörtern_
> 
> So _see this/that entry_

@fxru 

As I am now on pwk "overhaul" (attending to various markups, abbr.s and ls-entites), stumbled upon this--

`<div n="p">— Mit {#punar#} <ab>s.u.</ab> diesem Worte.`

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/6f2174f6-8ba4-415b-8541-210f6d182498)
[pwk Vol.4, p.273]

Just FYI, that you had almost resolved it to the same here in GRA.
What's the difference between **Wort** and **Worte**?

**Comment by Andhrabharati** [comment]
> What's the difference between **Wort** and **Worte**?

I found some answer here-
https://blogs.transparent.com/german/the-curiosity-of-the-plural-of-das-wort/

The distinction is so subtle, between the different usages.
One has to be cautious to get the correct one depending on the context!!
