### ISSUE TITLE
GRA VN data "integration" into main text

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/GRA#28]
### GRA VN del corrections:

1. I had started with marking the "del" category which is the smallest of the 3 types (change, deletion and addition), and seen a gross mistake in gra_9 version by Jim at `<d 325> <p>528,29. 30.b: *`, which clearly mentions the deletion to be in 529-b, lines 29 & 30.

Here are the lines in corrected (new) and Jim's (old) versions:
new	`<div n="TS">-ri [<ab>3. s.</ab> <ab>me.</ab>] medial: {@prá@} 4) {119,6}; <ab>pass.</ab>: {@prá@} 4) {308,6}; {805,5}; {885,1}; {952,8}. — {@ví@} 4) {970,5. 6} (váyas, ā́yus).`
new	`<chg type="del" n="325" src="gra"><old><div n="TS">-rīmahi [<ab>Opt.</ab>] {@prá@} 6) {214,10}.</old></chg>`

old	`<div n="TS">-ri [<ab>3. s.</ab> <ab>me.</ab>] medial: {@prá@} 4) {119,6}; <ab>pass.</ab>: <chg type="del" n="325" src="gra"><old>{@prá@} 4) {308,6}; {805,5}; {885,1}; {952,8}.</old></chg> — {@ví@} 4) {970,5. 6} (váyas, ā́yus).`
old	`<div n="TS">-rīmahi [<ab>Opt.</ab>] {@prá@} 6) {214,10}.`

And the same can be seen properly applied in the "corrected re-print" of Grassmann (1976 ed. & 1996 rev. ed.)

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/1287a5f7-d1ea-41bf-aa1f-c7d9b32057c5)

2. As for the other differences, at many places (more than half of them), the deletions did not cover the spaces and and other characters [like ';' '}' and '—' etc]. (and the newly added div tags in the text); I just imagined removing the deleted matter altogether, and this would leave double spaces, hanging characters and vestigial tags in the text!

**In my version now, I had properly marked all the deletions in the "new style" proposed by Jim.**

**Comment by Andhrabharati** [comment]
Not so important matter to bother about, but I feel the delete category should also be started with no. 1, as the change and addition categories.

**The print has the three categories clearly separated**, so the delete section numbers should not be in continuation of the change section numbers.

**Comment by Andhrabharati** [comment]
if @funderburkjim agrees to have the "del" numbers changed from 1 to 92, I will update my full file as the vn5 file accordingly for his revised displays.

**Comment by Andhrabharati** [comment]
**GRA VN chg corrections:**

1. Noticed cases where the corrections in HWs are not "completely" carried into the metalines, like the accents etc.

2. One error at `<chg 17> 34,11.10 v. u.: {%reingesinnt%} st. {%untrügliche%} u. s. w.`, which asks to remove all the matter from untrügliche onwards; @funderburkjim has just marked the untrügliche as the correction! When the HW is changed (as indicated), the matter thus changed has no relevance!!

See the translated texts--
ádabdha-dhīti : reingesinnt.
ádabdha-dhīti : pure minded.

ádabdha-dhīti : {%untrügliche Führung%} [nītí] {%gewährend, sicher führend%}.
ádabdha-dhīti : {%unfailing leadership%} [nītí] {%granting, sure leading%}.

Finally see the printed ed. correction of 1976 ed.
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/3b15902c-e238-4f98-aba1-4c2e7790c935)

**Comment by Andhrabharati** [comment]
With the above mentioned differences [more such are present in gra_9], I hope the reason behind my earlier post <https://github.com/sanskrit-lexicon/GRA/issues/21#issuecomment-1537762065> might be understood well.

Now, I won't be posting more on the topic, but just incorporate the corrections in my file.
[I am cross-checking all my "interpretaions" with the rev. ed. of 1996, which is quite helpful.]

**Comment by Andhrabharati** [comment]
@funderburkjim 

Noticed some error having crept in gra_9.

vṛj [Printed book page 1326] [ID=8351] of the orig. file has first (main) para that runs into 19 lines (on web display), [https://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2020/web/webtc2/index.php]

while the same in the rev. file has first (main) para that runs into 32 lines!!
[https://sanskrit-lexicon.uni-koeln.de/work/gra-dev/gra9/web/webtc2/index.php]

The rev. file has duplicated a big text block from the first portion, and has applied the `<chg 230>` in the later portion.

**Comment by Andhrabharati** [comment]
Courtesy the hardwork put in by Jim in marking the changes (which I had taken as a starting ref.), **I had finished incorporating the changes** in the whole file now.

**Comment by Andhrabharati** [comment]
Now, I am thinking of integrating the additions as well into the main file, in a similar fashion as the deletions and changes.

This being the largest portion in the GRA VN, it would require a much longer time to finish.

@funderburkjim 
is the markup `<chg type="add" n="nnn" src="gra"><new>YYY</new></chg>` alright?

I framed it to be similar to the other two types you have used--
`<chg type="del" n="nnn" src="gra"><old>XXX</old></chg>`
`<chg type="chg" n="nnn" src="gra"><old>XXX</old><new>YYY</new></chg>`

Hope to get your response at least on this point.
[I see that for the past few days, I am not getting any response on (m)any posts that I posted.]

**Comment by Andhrabharati** [comment]
One important point to be kept in mind while adding the VN **add** portions to the main text--

```
<h>(das Zeichen * bedeutet dass das Wort oder die Form im Wörterbuche ganz fehlt).</h>
<h>ENGLISH: (the character * means that the word or form in the dictionary completely missing).</h>
```

Thus, the * has a different purpose in the main text (indicating that the word or word-form does not occur in the RV) and the VN text (indicating that the word or word-form does not occur in the main text).

So the * (in VN) has to be removed while inserting the VN **add** portions within the resp. main text data.

**Comment by gasyoun** [comment]
> In my version now, I had properly marked all the deletions in the "new style" proposed by Jim.

Dear @Andhrabharati I bow to your dedication to Sanskrit lexicography and how team-work friendly you've become.

**Comment by funderburkjim** [comment]
> deletion to be in 529-b, lines 29 & 30.

Agree.  I erroneously marked 'a' lines.  BTW, it is page 528.

**Comment by Andhrabharati** [comment]
Yes, my mistake in commenting here; but not in the actual work!

**Comment by funderburkjim** [comment]
> delete category should also be started with no. 1

Agree.   The purpose of the number is to 'tie' (a) the text `<chg>` markup and (b) the corresponding VN text.

**Comment by funderburkjim** [comment]
Regarding `<chg>` markup for additions.  

If you do provide such markup, your form looks reasonable.

However, it is not clear to me that such markup should be added.
Look at the current gra9 display for aMSu:
https://sanskrit-lexicon.uni-koeln.de/work/gra-dev/gra9/web/webtc/indexcaller.php.

In this example, the 'vn add 1 gra'  record (L=12001) seems adequate.

So my current opinion is that there does NOT need to be any additional markup for the Nachtrage.

**Comment by funderburkjim** [comment]
> ádabdha-dhīti,

Your use of the '1976' edition is proving quite useful in improving the markup, in this example and others.

**Comment by funderburkjim** [comment]
Are there any other concerns where you need my response now?

**Comment by Andhrabharati** [comment]
My view is that the **add** corrections should also be done in-line, as were the del and chg corrections.

This would at once shows the place where the correction is present, instead of the user looking at the **L-12xxx** display at the bottom and then put his mind to properly position the correction in the above matter.

When there are multiple additions like at entry **agni**, you could appreciate the point much better, where the user would otherwise have to "traverse" up and down multiple times to see the correction places, and **more often than not** one would definitely miss some of them!!

And also the VN data would be more **visible** if it is also split as the main text, see how I did them taking the same agni example--

```
<L>12009<pc>1749<k1>agni<k2>agni/
{@agní@}¦:<info vn="add 9 gra"/>
<div n="TS">-áye 2〉 {304,5}; {359,1. 11}; {361,1}; {663,11}; …
<div n="TS">*-és [<ab n="Ablativ">Ab.</ab>] {888,5. 6}; {902,5}; {1007,2}.
<div n="TS">-és [<ab n="Genetiv">G.</ab>] 2〉 ávena {128,5}; ajárās {143,3}; juhúas {507,10}; ánīkam {604,2}; {833,3}; dhā́rām {682,9}; várma {842,7}; śármaṇi {862,12}; samídhas {877,2}; samídh (-ít) {906,2}; bhrā́taras {877,6}. ā́yus {8}; saṃdṛ́śas {895,1}. várdhanam {2}; dhā́māni {906,4}. gávyūtis {6}; 〰 gāyatrī́ abhavat {956,4}.
<div n="TS">-aú 2〉 {481,3};
<div n="TS">-ā́ 2〉 {681,15};
<div n="TS">-ī́ 2〉 índra yás 〰 {501,1};
<div n="TS">-áyas 1〉 {341,5}.
<LEND>
```

**Comment by Andhrabharati** [comment]
However, if you are "happy" with the **add** corrections left un-integrated, it would save me few days' time!!

**Comment by funderburkjim** [comment]
Here's a possible 'intermediate' idea for 'add' markup.
`<chgref type="add" n="9" src="gra">`
 The display would render this as a message in red, such as
 `[Please see below: vn add 9 gra] `


This markup could be placed in the body text at the end of relevant sections.
e.g., in the agni L= 12009 example, at the end of each of these sections.
`-áye, -és, aú, -ā́, -ī́, and -áyas`  

Such markup 
* would alert the reader to the extra material at the bottom of the display.  
* would not duplicate the VN text in the body text.

What do you think?

**Comment by Andhrabharati** [comment]
Yes, it would reduce the markup time drastically; but it has some drawbacks still!!

**Comment by Andhrabharati** [comment]
To avoid too much cluttering the text with the chg tags spread all through the matter, I would like suggest a different solution--

> to have a spl. character denoting each category, say del- ●; chg- ■ and add- ⧫;
> and just ignore the change numbers in the in-line matter.

[This improves the readability of the file also, for people like me, though it is only once in a while activity.]

**The display code can take care of the rest!!**

And just put the VN change files at the bottom, as they are already 'linked' to the resp. entry word.


What do you think of this, @funderburkjim ?
[As the VN/Addenda integration is to be done in other dictionaries also, we should see how easily and quickly the task could be done.]

**Comment by funderburkjim** [comment]
I need to see example(s).

**Comment by Andhrabharati** [comment]
The in-line VN change matter could be as simple as--

●{XXX} ;;del- ● & XXX old matter
⧫{YYY} ;;add- ⧫ & YYY new matter
■{XXX//YYY} ;;chg- ■ & as // never occurs in any text, it could be the delimiter between the old and new matter

**Comment by Andhrabharati** [comment]
del example:

```
<L>14<pc>0003<k1>aMhas<k2>a/Mhas
{@áṃhas,@}¦ <ab n="neutrum">n.</ab>, die {%Bedrängniss%} (<ab n="siehe">s.</ab> <ab n="das">d.</ab> <ab n="vorige">v.</ab>), doch scheint in {443,4} noch die Grundbedeutung {%Enge, enge Kluft%} erhalten: dvíṣas áṃhas ná tarati, über die Feinde setzt er hinweg, wie über eine enge Kluft (<ab n="vergleiche">vgl.</ab> {224,3}).
<div n="TS">-as {42,1};● {63,7};● {214,4. 5}; {219,6}; {224,2}; {225,15}; {293,2}; {298,9}; {299,14}; {307,6}; {308,6}; {316,9}; {385,13}; {399,11}; {443,4}; {444,2}; {445,8}; {452,6}; {478,4}; {485,16}; {508,8}; {556,4}; {582,5}; {598,7}; {639,6}; {816,6}; {861,14}; {865,11}; {889,6}; {952,1. 8}.
<div n="TS">-asas [<ab n="Ablativ">Ab.</ab>] {18,5}; {36,14}; {58,8. 9}; {91,15}; {93,8}; {106,1}; {115,6}; {118,8}; {136,5}; {180,5}; {217,4}; {266,14}; {298,8}; {349,6}; {351,5}; {405,13}; {457,30. 31}; {489,8}; {517,15}; {531,3. 13. 15}; {532,10}; {587,5}; {620,23}; {638,6. 10}; {644,27}; {651,2}; {768,4}; {850,3}; {851,8}; {862,2. 3}; {879,5}; {891,12}; {892,5}; {923,15}; {958,7}; {990,4}.
<div n="TS">-asas [<ab n="Genetiv">G.</ab>] pārám {224,3}.
<div n="TS">-asi {54,1}.
<div n="TS">-āṃsi {443,11}; {539,2}.
<LEND>
```

add  & chg example:
```
<L>5<pc>0001<k1>aMSu<k2>aMSu/
{@aṃśú,@}¦ <ab n="masculinum">m.</ab>, Name der {%Pflanze, aus welcher der Soma gepresst wurde%}. Sie wird häufig mit der Kuh verglichen, aus welcher der Somasaft herausgemolken wird (so {397,4}; {137,3}; {629,19}; {819,12}; {204,1}; {282,2}; {920,8} <ab n="und so weiter">u. s. w.</ab>). Dann aber wird der Name auch beibehalten, um den herausgepressten Saft (dugdhás aṃśús {270,6}; {390,1}; {614,1}) zu bezeichnen. Einmal ({625,26}) erscheint er auch als Eigenname eines Sängers. Von der spätern Bedeutung: Sonne, Sonnenglanz, Sonnenstrahl zeigt sich nur in sumád-aṃśu ({100,16}) eine Spur. Also: 1〉 {%Somapflanze,%} 2〉 der aus ihr gepresste {%Somasaft,%} 3〉 {%Eigenname%} eines Sängers. Zwischen 1〉 und 2〉 finden mannichfache Uebergänge statt; ja strenggenommen ist bei der zweiten stets die erste als Grundbedeutung festzuhalten und im Bewusstsein der Dichter lebendig. <ab n="Vergleiche">Vgl.</ab> die Beiwörter madirá, mádhumat, tigmá, sutá, vṛ́ṣan, ukṣán und die Genetiven mádhvas, mádhunas, sómasya. [Page2]
<div n="TS">-ús 1〉 {397,4}; {780,4}; {786,2}; {803,3}⧫; {920,9}⧫. 2〉 {270,6}; {318,8}; {774,4}; {786,5}; {801,6}; {804,1}; {843,12. 13}; {920,10}.
<div n="TS">-úm 1〉 {137,3}; {270,7}; {322,6}; {780,6}; {784,6}; {807,4}. 2〉 {390,1}; {458,11}; {461,6}; {614,1}; {681,2}; {798,46}; {809,14}; {939,2}; {975,5}. 3〉 {625,26}.
<div n="TS">-únā 1〉 {354,1}.
<div n="TS">-áve 1〉 {46,10}.
<div n="TS">-ós 1〉 sutám {125,3}; pīyū́sam ■{204,2}//{204,1}■; {282,2}; {920,8}; ándhas {297,19}; páyasā {819,12}. — 2〉 ūrmím {808,8}; pibanti {321,3}.
<div n="TS">-ávas 1〉 {629,19}; {1022,4}.
<div n="TS">-úbhis 2〉 {91,17}; {727,5}; {779,28}.
<LEND>
```

**Comment by funderburkjim** [comment]
Have you already implemented (with corrections) the 'changes' and 'deletions' marked in the text as in gra9 ?
e.g.
```
<chg type="chg" n="4" src="gra"><old>bramā́s</old><new>bhramā́s</new></chg>

and
<chg type="del" n="273" src="gra"><old>{63,7};</old></chg>
```

Or is this yet to be done in your file?

**Comment by Andhrabharati** [comment]
I did both of them yesterday itself <https://github.com/sanskrit-lexicon/GRA/issues/28#issuecomment-1573963314> and now preparing to do the VN **add** matter.

**Comment by funderburkjim** [comment]
Ok.  Let's just leave the chg/del  as you have done. I think this works well.

As for the adds,  let's just leave NO markup in the body text.

**Comment by funderburkjim** [comment]
With the VN material integrated into your version, is your version done?
Are you almost ready to hand the baton back to me?

**Comment by funderburkjim** [comment]
I'll be away from my desk for a while.

**Comment by Andhrabharati** [comment]
> Ok. Let's just leave the chg/del as you have done. I think this works well.
> 
> As for the adds, let's just leave NO markup in the body text.

I did not understand this!!

1. Are you saying to leave the del/chg corrections as is, or to modify them as I suggested?
2. No markup for add matter but insert it as plain text, or not to integrate the add matter at all?

**Comment by Andhrabharati** [comment]
> With the VN material integrated into your version, is your version done?
> Are you almost ready to hand the baton back to me?

I am awaiting the abbr. conclusion/resolving, if the VN **add** is not to be done.

**Comment by Andhrabharati** [comment]
> I'll be away from my desk for a while. 

I am retiring for the day (it's past midnight, 1:20 AM) for me now.

**Comment by funderburkjim** [comment]
I meant: 
1. leave the del/chg corrections as is
2.  not to integrate the add matter at all

**Comment by Andhrabharati** [comment]
> I meant:
> 
>     1. leave the del/chg corrections as is
> 
>     2. not to integrate the add matter at all

Good decision, @funderburkjim !

The only reason I could think of behind this is your reluctance/resistance/inertia/... (and what else!) of changing something that you have already developed, unless some good amount of persuasion is put in by the other person; **but, be it so** [as I already gave my word for it <https://github.com/sanskrit-lexicon/GRA/issues/28#issuecomment-1575086042>; you'll get the data without the add changes [but as I had already initiated the process at my end, I will finish the add insertions also and keep aside a separate file, who knows— one might need it someday!]

And do you want the vn6 data properly split (the way I did), or you'd like to continue with what you have done on your 'own'?

**Comment by Andhrabharati** [comment]
@funderburkjim

I just did some minimal adjustments & checks on my GRA file today; and I did not touch the **del** numbers (though you had agreed in principle for doing it).

**Now the baton could be back to you anytime, once the reported abbr. entities are resolved.**

**Comment by Andhrabharati** [comment]
Here are my vn3.2 (VN **add**) files--
[vn3.2_AB (padded metaline & header from vn6).txt](https://github.com/sanskrit-lexicon/GRA/files/11648751/vn3.2_AB.padded.metalines.from.vn6.txt)
[vn3.2_AB (updated).txt](https://github.com/sanskrit-lexicon/GRA/files/11648754/vn3.2_AB.updated.txt)
[Note: In my final version, couple of metaline data got changed to match my **add** header & hope it would not affect Jim's search results, wherein he had the metaline (ka, k2) set matching in vn6 and main texts.]

and vn3.3 (VN **index**) portion--
[vn3.3_AB (done).txt](https://github.com/sanskrit-lexicon/GRA/files/11648785/vn3.3_AB.done.txt)
[This has no use in CDSL GRA, as it is to be used in the GRA index portion (left in CDSL digitisation).]

**Comment by funderburkjim** [comment]
I'm going to work on user corrections (3 month backlog!).  When that is done, I will be ready to begin work with your version of Grassman.  Probably two or three days.
Will let you know.

**Comment by funderburkjim** [comment]
> and I did not touch the del numbers

This is a matter where my communication was not clear.  I like the idea of changing the 'del' numbers starting with '1'.

**Comment by funderburkjim** [comment]
> reluctance/resistance/inertia/...  unless [persuaded]

Yes

**Comment by funderburkjim** [comment]
>  will finish the add insertions also and keep aside a separate file, who knows— one might need it someday!]

Good idea to do this while the details are fresh in your mind.

**Comment by Andhrabharati** [comment]
> > and I did not touch the del numbers
> 
> This is a matter where my communication was not clear. I like the idea of changing the 'del' numbers starting with '1'.

You were quite clear in what you said; I was only saying that I did not do the work, though you had 'agreed' for (my doing) the point!!

**Comment by Andhrabharati** [comment]
> I'm going to work on user corrections (3 month backlog!). When that is done, I will be ready to begin work with your version of Grassman. Probably two or three days. Will let you know.

I am seeing that the user correction are inclusive of GRA; so, most probably you have to **repeat** those again, when my version is taken up.

**Comment by Andhrabharati** [comment]
> > will finish the add insertions also and keep aside a separate file, who knows— one might need it someday!]
> 
> Good idea to do this while the details are fresh in your mind.

I started adding them with **{A…A}** marking, similar to the bold **{@…@}** and italics **{%…%}** tagging!
