### ISSUE TITLE
CDSL display of AB version

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GRA#29]
@Andhrabharati 

It seems ([ref](https://github.com/sanskrit-lexicon/GRA/issues/27#issuecomment-1582411044)) it is now my turn to take up the baton with Grassman.
Please upload the file (or files) which comprise your version.

**Comment by Andhrabharati** [comment]
It is just a single file, containing all the information @funderburkjim !
[gra_(CSL)_[AB]-8b (chg corrections done).txt](https://github.com/sanskrit-lexicon/GRA/files/11708346/gra_.CSL._.AB.-8b.chg.corrections.done.txt)

But these two files might be helpful--
[GRA lang tags with expansion.txt](https://github.com/sanskrit-lexicon/GRA/files/11708409/GRA.lang.tags.with.expansion.txt)
[GRA pe tags.txt](https://github.com/sanskrit-lexicon/GRA/files/11708416/GRA.pe.tags.txt)

And, pl. keep in mind that the {...} numbers need to be properly combined (or padded) with the preceding ls-entity, esp. the AV. which you had observed earlier to be separated out (in my file data).

And the ls-entities (~140 of them in total, many of which are just the variant forms!) can be easily expanded, if required. 
[Most probably, as I presume, no other work is worth linking in this GRA other than RV & AV.]

**Comment by Andhrabharati** [comment]
And, once you're done with this, many issues in this repo could be closed at once.

**Comment by funderburkjim** [comment]
## well-formed xml
I found it necessary to make a  few changes (27 lines) so the constructed gra.xml is well-formed.
Please see [change_1.txt](https://github.com/sanskrit-lexicon/GRA/blob/master/graab/change_1.txt)

change_1_notes.txt provides (brief) commentary.

@Andhrabharati  Any objections to these changes?

**Comment by Andhrabharati** [comment]
Not any strong ones, except that empty tags are remaining after the deletions; I had mentioned this before also when your gra9 was given out.

But, as it is only inside the txt file and not shown to the "online" user when searched, I can "live with it".

**Comment by funderburkjim** [comment]
Please confirm which uploads have your  lastest vn material -- I need to paste those to the end of your file (L=11001 through L= 12701)

**Comment by funderburkjim** [comment]
I presume they are (from #28)
* adds: vn3.2_AB.updated L=12000-12701
  * vn3.3_AB.done  (material after 12701)

But I don't see similar from you for L=11000-11xxx  (chg and del vn).  
Should I use these from my gra9?

**Comment by funderburkjim** [comment]
It's getting late again here.  Will check tomorrow.

**Comment by Andhrabharati** [comment]
Do you mean this?--
[vn5_AB.txt](https://github.com/sanskrit-lexicon/GRA/files/11711404/vn5_AB.txt)

**Comment by Andhrabharati** [comment]
And I hope you have noticed my "Note" at https://github.com/sanskrit-lexicon/GRA/issues/28#issuecomment-1576066895

**Comment by funderburkjim** [comment]
Yes, vn5_AB is what I mean. Thanks for it.

**Comment by funderburkjim** [comment]
@Andhrabharati   
* graab_2 merges your VN material . 
  * gra.xml still well-formed.
  * graab_meta_compare/readme_diff.txt shows the L,k1 differences between graab_2 and gra9.
* graab_3 makes 3 corrections. See change_3.txt  ( These seem non-controversial to me).
* You may also want to review readme_printchange_notes.txt
* guhya/guhia and vIrya/vIria  remain open problems (I think these are the 'couple of metaline' mentioned in "Note" at issue28-comment link above).
  * May get resolved by some yet to be written 'hwextra' code.
 
Next step is to modify gra.dtd so the gra.xml is also 'valid' relative to the dtd.

**Comment by Andhrabharati** [comment]
change_3.txt

`<hom>2.</hom> <ab n="dual">du.</ab>` is a big mistake on my part.

**Comment by Andhrabharati** [comment]
@funderburkjim 

When I was looking at PWG yesterday to check your post, noticed that abbr. "1." has to be expanded as '1sten/ersten', not as '1ten/ersten'.

Pl. make a note of this and add it in your TODO list of GRA.

**Comment by Andhrabharati** [comment]
> readme_printchange_notes.txt

1571 : AyAjyu : AyAjyu : Ayajyu
verified with the cited text and found ok
`-------------------------------------`
4933 : nAva : nAva : nAvA
`<L>4933<pc>0726<k1>nAvA<k2>nAvA/` {@nāvā́,@}
Verified again and found that I had read it wrongly earlier!
[In a hurry, I just saw the AV text inside, ignoring the actual RV citation.]

It should instead be `<L>4933<pc>0726<k1>nAva<k2>nAva^` {@nāvà,@}
-------------------------------------
```
OLD
<L>5395.1<pc>0797<k1>paSya<k2>paSya
<L>5396<pc>0797<k1>paSvaizwi<k2>pa/Sva-izwi
```

What made you feel that the alphabetical order is wrong in these entries?

**Comment by funderburkjim** [comment]
## re paSya
'y' comes before 'v' in Sanskrit alphabetical order.
Print has paSva-izwi before paSya.  So print is wrong.  You put paSya first, so your change restores
alphabetical order.  Your change corrects the print, so should be mentioned as a print change.

## re L=4933.   
I think it should be nAvA, since we have 'f.'   
Also, compare PWG (look up nAva -- nAvA/ appears).
So I agree with the print change, do not agree with `<L>4933<pc>0726<k1>nAva<k2>nAva^`.

**Comment by Andhrabharati** [comment]
> I think it should be nAvA, since we have 'f.'
> Also, compare PWG (look up nAva -- nAvA/ appears).
> So I agree with the print change, do not agree with `<L>4933<pc>0726<k1>nAva<k2>nAva^`.

Yes, the citation has no svarita accent (udAtta accent would not be shown in devanagari print!) and the entry TS form is clearly **a/ya**.

**Comment by Andhrabharati** [comment]
> Your change corrects the print, so should be mentioned as a print change.

So, are you putting it as `<L>5394.1`?

And in such a case, shall I 'trace' the other such places also (that I remember to have seen)?

**Comment by Andhrabharati** [comment]
> May get resolved by some yet to be written 'hwextra' code

Pl. make the code generic to handle the grouped entries in other works as well, esp. the MW, (in which in my current revision) I had removed all the replicated entries of the groups, retaining only a single entry.

**Comment by funderburkjim** [comment]
> So, are you putting it as <L>~~5394.1~~? 5395.1

Yes

> shall I 'trace' the other such places ... ?

It is up to you.

**Comment by funderburkjim** [comment]
> '1sten/ersten', not as '1ten/ersten'.
Have revised GRA.pe.tags.txt accordingly.

**Comment by funderburkjim** [comment]
## abbreviations
Beginning work on abbreviations in [abbrevs](https://github.com/sanskrit-lexicon/GRA/tree/master/graab/abbrevs) directory

First, examining the `<ab n="tip">abbrev</ab>`, including counts.

* extract_abbrev.txt has all those which should be 'compressed' to `<ab>abbrev</ab>` in graab_n.txt. The tooltip will be derived from the revised 'global tooltips' (graab_input.txt in csl-pywork).
* extract_abbrev_local.txt has those which are 'local' (i.e., they remain in form `<ab n="tip">abbrev</ab>`  in graab_n.txt.  
  * Note: *local* determined by frequency count for the abbrev

@Andhrabharati  Two questions:
* In my revision of your file, I am planning to change `<ab n="tip">abbrev</ab>` to `<ab>abbrev</ab>` for the global abbreviations.  Do you agree with this planned change to your file?
* There are some unmarked abbreviations in the VN portion. The ones I noticed are
  * st.  (tooltip = 'statt' - only 1 is marked currently  `273 matches for "\bst\."
  * v. u. (tooltip = 'von unten' )   `177 matches for "\bv\. u\."`
  * I plan to change your file by marking these. Do you agree?

**Comment by Andhrabharati** [comment]
These additional **st.** and **v. u.** are from the vn5 portion, as I see; and, you can go ahead, if you wish.
[I did not feel the necessity to mark the abbreviations in the vn portion, hence left them in my working.]

**Comment by Andhrabharati** [comment]
Speaking of this VN portion, I think, the VN **add** portion also might need the abbr. expansions.

**Comment by Andhrabharati** [comment]
Just saw that the VN **add** text needs the `<hom>` tagging as well.

**Comment by Andhrabharati** [comment]
> * In my revision of your file, I am planning to change `<ab n="tip">abbrev</ab>` to `<ab>abbrev</ab>` for the global abbreviations.  Do you agree with this planned change to your file?

See my earlier post [saying thus](https://github.com/sanskrit-lexicon/GRA/issues/27#issuecomment-1582411044)

> @funderburkjim may decide whether to retain the expansions completely as I did, or make the larger count abbr.s as global and the rest as the local abbr.s when he takes up my file; and **with this my work on GRA is over for now.**

**Comment by Andhrabharati** [comment]
Sorry, I looked at wrong (prelim.) file; the vn3.2_AB (updated).txt has all the markings done.

**Comment by Andhrabharati** [comment]
People might find it odd, as that is not normally used/seen anywhere!

And, it was just an intermediate replacement I had opted to resolve the parenthesis mismatching.

**Comment by funderburkjim** [comment]
OK -  I'll change 〉 to ).

Noticed some unresolved RV forms in vn add section. e.g. `{556,2. 4}`
Will put this in my TODO list.

**Comment by Andhrabharati** [comment]
Just seen your separation files for global and local abbr.s

(f.:feminium) -- local should be changed to (f.:femininum) -- global; it is a manual marking error on my part.

**Comment by Andhrabharati** [comment]
You did not update the lang expansion file, with the the latest one I posted.

**Comment by funderburkjim** [comment]
Your link is the one I downloaded (GRA.lang.tags.with.expansion.txt).
Should it GRA.lang.tags.with.expansion.done.txt be the one I use?

**Comment by Andhrabharati** [comment]
No, its the same name but updated without any '?' as at https://github.com/sanskrit-lexicon/GRA/issues/29#issuecomment-1584859625

**Comment by funderburkjim** [comment]
@Andhrabharati  

At #5, you commented `I've tagged all such numbers still present in the CDSL version with { }`  [ref](https://github.com/sanskrit-lexicon/GRA/issues/5#issuecomment-1566632950).

But I do not find these marked as expected in your version.

 e.g. 4488 of these RV references have a space within the curly brackets:

`4488 matches in 2179 lines for "{[0-9][^}]* `.  

First example on line 26: `{843,12. 13}; {920,10}.`   

I had expected to see ``{843,12.} {13}` in your version

What did you mean by the `I've tagged ..` comment?

**Comment by Andhrabharati** [comment]
What I meant is all the 'number groups' or 'isolated numbers' are enclosed by the { }; and I presumed that you would be separating & then expanding them by appropriately 'padding' the initial numbers and/or the ls-entity name to each of the 'linkable' citation(s).

**And this is the style I "follow" in my works normally**; you may recall the **pwk** etc. which I had done earlier.

**Comment by funderburkjim** [comment]
OK.  The 'separation' part is up to me also.  Makes sense. Thanks for clarification.

**Comment by Andhrabharati** [comment]
Not avl. immediately, but see what I had said (above)[https://github.com/sanskrit-lexicon/GRA/issues/29#issuecomment-1584859625] at the end

**Comment by funderburkjim** [comment]
Here is a list of the ls:
* [extract_ls0.txt](https://github.com/sanskrit-lexicon/GRA/files/11762126/extract_ls0.txt)  the Global ones
  * these need tooltips
* [extract_ls0_local.txt](https://github.com/sanskrit-lexicon/GRA/files/11762135/extract_ls0_local.txt)  The local ones.

The format of each line is "abbrev:tip:count".

@Andhrabharati  Request you to edit and provide tooltips?  (between the two colons)
Note: In tooltip, please use left/right single quote rather than apostrophe (Reason: display program gets confused by apostrophe in tooltip.)

**Comment by funderburkjim** [comment]
Noticed some expansions for 'ls' items (from previous general abbreviation tooltips.  These expansions from the frontmatter of Grassman.
```
Cu.	<id>Cu.</id> <disp>Curtius, Grundzüge der griechischen Etymologie</disp>
Fi.	<id>Fi.</id> <disp>Fick, Vergleichendes Wörterbuch der indogermanischen Sprachen 1870</disp>
Ku.	<id>Ku.</id> <disp>Kuhn, Zeitschrift für vergleichende Sprachforschung</disp>
BR.	<id>BR.</id> <disp>Böhtlingk und Roth, Sanskrit-Wörterbuch</disp>
Be. SV. gl.	<id>Be. SV. gl.</id> <disp>Benfey, Glossar zum Sāma-Veda </disp>
Be. SV. gloss.	<id>Be. SV. gloss.</id> <disp>Benfey, Glossar zum Sāma-Veda </disp>
Be.	<id>Be.</id> <disp>Benfey</disp>
```

**Comment by funderburkjim** [comment]
## abbreviations 
This includes tags `<ab>, <lang>, and <pe>`.  All three tags appear in gra.xml.

Work is done in [abbrevs](https://github.com/sanskrit-lexicon/GRA/tree/master/graab/abbrevs) directory.
* graab_input_old.txt  is the old (gra9) abbreviation file used by displays
* graab_input.txt is the new abbreviation file. It will be copied to csl-pywork repository

basicadjust.php (in csl-websanlexicon repository) changes `<pe> and <lang>` tags to `<ab>` for gra, so the tooltips will display.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Pl. post your graab_3.txt, after you finish whatever work by the end of your day.

I would like to update the same and post back tomorrow daytime at my end, by making few changes that I had marked in my local files while expanding the ls-items.
[Few are changed to abbr.s & few made local ls-items.]
Also marked the non-RV/AV citations within〔...〕; i.e. some differentiating brackets.

Then you can continue with your GRA work at your daytime tomorrow; or probably you may wish to keep this pending till you finish all your working.

**Comment by funderburkjim** [comment]
I would prefer to post my graab_5 version.  It differs from graab_3 by
* global abbreviations applied  (e.g. `<ab n="X">Y</ab>` changed to `<ab>Y</ab>` for the global abbreviations
* global ls abbreviations applied (e.g. `<ls n="X">Y</ls>` changed to `<ls>Y</ls>`
   * possibly (if I get to it) `<ls>Y</ls> {NN}</ls>` -> `<ls>Y {NN}</ls>`   
   
Is graab_5 ok with you?

**Comment by funderburkjim** [comment]
Yes, the ls tooltips not pressing in my work.

**Comment by Andhrabharati** [comment]
> Is graab_5 ok with you?

Certainly; what I meant is the latest one from you.

**Comment by gasyoun** [comment]
@funderburkjim https://github.com/sanskrit-lexicon/GRA/tree/master/graab/abbrevs

Why `ndd.` twice?

```
< <lang>ndd.</lang>     ???
---
> <lang>ndd.</lang>     Low German
47d48
```

**Comment by funderburkjim** [comment]
## literary source markup changes, part 1
This work done in the graab/litsrc directory.
Three change files:
* graab/change_5a.txt : `<ls n="T">X</ls>` -> `<ls>X</ls>`
* graab/change_5b.txt:  `<ls>AV.</ls> {a,b,c}` -> `<ls>AV. a,b,c</ls>`  
* graab/change_5c.txt:  `<ls>AV.</ls> {a,b,c. d}` -> `<ls>AV. a,b,c</ls> <ls n="AV. a,b">d</ls>`

Changes made to display programs so these 'ls' items display appropriately, with links for AV, and tooltips for all.

@Andhrabharati  here is the latest version:
[temp_graab_5.zip](https://github.com/sanskrit-lexicon/GRA/files/11777724/temp_graab_5.zip)

**Comment by funderburkjim** [comment]
> why ndd. twice ?

@gasyoun   The 'final' abbreviation file to look at is [graab_input.txt](https://github.com/sanskrit-lexicon/GRA/blob/master/graab/abbrevs/graab_input.txt).  A copy of this file is what the displays use for tooltips.
There are no duplicates in this file.


Similar information, but with counts, is found in extract_abbrev.txt, extract_lang.txt, extract_pe.txt in the same directory.

**Comment by Andhrabharati** [comment]
Sorry to say this, @funderburkjim --

I could not find time to the work today.

But now that I have your **ref. version** to put my corrections, I will try to do it tomorrow or day after; and it would be easier to 'transfer' the changes into your updated version (which you would be undertaking meanwhile).

**Comment by funderburkjim** [comment]
Sure, no problem.

**Comment by Andhrabharati** [comment]
@fxru 

Could you pl. help locating the Magazine (or some similar publication) by the name "Beiträge"?

Grassmann has referred to an article in it (Vol. 7, pp. 252-253) in two places--

[S. 1617]
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/90b63387-6b3d-4279-a84e-f9854ea0e787)

[S. 1124]
![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/727bf0fe-df45-4dd3-a1c5-9bc7301ef095)

I tried locating the Seigfried Goldschmidt's article; and an article [**1. chromŭ - srāma; 2. yuvā́ku**] is traced [which incidentally contains a ref. to an article by Kuhn in the "Beiträge"] to be in a French Memoir book (_Mémoires de la Société de linguistique, Paris, 1868_) [and this particular **Mém. Soc. Ling. article** appears to have been quoted at many places], but could not locate any German Mag. (or a similar type) having "Beiträge" in itʼs name.

And this article is in the "Varieities" section of the **Mém. Soc. Ling.**, which seems to contain various articles from different publications. [Many old time magazines were noted to be containing a **Section** with such selections from other publications, as a regular feature.]

**Comment by Andhrabharati** [comment]
BTW, Grassmann has cited the "Beiträge" (Vol.1) at another place, apparently for the same Kuhn's article (as above)--

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/1f942d6e-ec91-4d92-a851-c0e1902b9670)

**Comment by Andhrabharati** [comment]
@funderburkjim 

While looking for an entry for checking in the page, accidentally noticed an error in the VN **add** section in your graab5 file; while generating the meta-lines for the entries, wherever **[Pagexxxx]** is present without a blank line next, all the further entries are put under the previous pc-number.

This is seen for entries in pp. 1752-3 (as 1751), pp. 1755-6 (as 1754), pp. 1758-9 (as 1757), pp. 1764-5 (as 1763).

However, such error is not there in the previous VN portion (**del** & **chg**) of data.

I had just picked up those lines from your vn5 and vn6 files while **making** my files earlier, I did not notice the error.

**Comment by Andhrabharati** [comment]
I found few silly errors in my file(s) earlier, that were taken by you as is.

Some abbr. expansions contained a space at the end (within the quotes), so they remained as different/local--

dopp.:doppeltem :2
Gegens.:Gegensatz :19
Opt.:Optativ :157
Optat.:Optativ :1

And in the **add** section that I took up at the end for markup (after a long gap) some carelessness crept in, and I had marked 4 entities badly, that turned up as local in your work being different from the others--

f.:feminium:31 ;; should've been femininum
Part.:Perfektum:24  ;; should've been Perf.
pass.:passiv:2 ;; should've been passivisch
Pass.:Passiv:5 ;; should've been Passivisch

**Comment by gasyoun** [comment]
> this particular Mém. Soc. Ling. article appears to have been quoted at many places], but could not locate any German Mag. (or a similar type) having "Beiträge" in its name.

@Andhrabharati what if no German was meant at all? Just a translation of the French title.

**Comment by gasyoun** [comment]
@funderburkjim here 'Roth' Surname is left unmarked twice. How to mark it?

![вввывввв](https://github.com/sanskrit-lexicon/GRA/assets/80761/14153821-0e8e-4698-8d57-bc5721970a27)

**Comment by Andhrabharati** [comment]
> @Andhrabharati what if no German was meant at all? Just a translation of the French title.

Did you read my full post?

The German work does exist, and should've been in wider circulation too; only I could not identify the same. 

Its definitely not the French work cited by GRA, as the cited page nos. do not match with the French work's page nos. [That's the reason foŕ my giving the page nos. above]

**Comment by Andhrabharati** [comment]
@gasyoun 

All these (and far many more!!) markings are "done" in my working, and will be avl. shortly to the public through Jim's revision of CDSL version of GRA.

**Comment by Andhrabharati** [comment]
@funderburkjim 
While matching the markings wrt to your graab_5, noted that **AV** tagging is not done for the "numerals string" after the semi-colon at 5 places .
```
Line 17652: <ls>AV. 9,3,20</ls>; {14,1,57}.
Line 58890: <ls>AV. 8,7,24</ls>; {11,1,2}.
Line 78400: <ls>AV. 4,16,1</ls>; {7,108,1}
```

**Comment by Andhrabharati** [comment]
> Here is a list of the ls:
> 
>     * [extract_ls0.txt](https://github.com/sanskrit-lexicon/GRA/files/11762126/extract_ls0.txt)  the Global ones
>       
>       * these need tooltips
> 
>     * [extract_ls0_local.txt](https://github.com/sanskrit-lexicon/GRA/files/11762135/extract_ls0_local.txt)  The local ones.
> 
> 
> The format of each line is "abbrev:tip:count".
> 
> @Andhrabharati Request you to edit and provide tooltips? (between the two colons) Note: In tooltip, please use left/right single quote rather than apostrophe (Reason: display program gets confused by apostrophe in tooltip.)

I took your combined file extract_ls.txt, as I felt it is more appropriate to change some of the entities as local from global.

Also noticed some corrections, while marking the ls-expansions.

**Comment by Andhrabharati** [comment]
4 of the SV citations have a different numbering (without comma separation) while 31 have the regular numbering and 169 have no numbering at all.

We may think of inserting the commas. to make all the citation numbers in same 'style'--

```
<ls>SV.</ls> 〔13142〕 -> <ls>SV.</ls> 〔1,3,1,4,2〕
<ls>SV.</ls> 〔13249〕 -> <ls>SV.</ls> 〔1,3,2,4,9〕
<ls>SV.</ls> 〔13256〕 -> <ls>SV.</ls> 〔1,3,2,5,6〕
<ls>SV.</ls> 〔14141〕 -> <ls>SV.</ls> 〔1,4,1,4,1〕
```

**Comment by Andhrabharati** [comment]
There are 6 entries which strictly are not ls-candidates--

Bollensen's Conjectur	:[Bollensenʼs Conjecture]	:1
BR.'s Conjectur	:[BR.ʼs Conjecture]	:1
BR.'s Vermuthung	:[BR.ʼs guess]	:2
Lesart bei Aufr.	:[Reading in Aufrecht edition]	:1
Roth's Conjectur	:[Rothʼs Conjecture]	:1
Roth's Erläuterungen	:[Rothʼs explanations]	:1

Should these be untagged?

**Comment by Andhrabharati** [comment]
While there are 297 `>BR.<`, 5 places have a space in between (`>B. R.<`).

Can the space be removed at these 5 places, to make all the items uniform?

**Comment by Andhrabharati** [comment]
one item has a spelling correction 
`Deutschen Pflanzennamen -> Deutsche Pflanzennamen` (and gets merged with the other one)

and another item has a portion untagged
`Laute Ku. -> Ku.` (and gets merged with the other one)

**Comment by funderburkjim** [comment]
> 6 entries which aren't ls-candidates strictly ... should they be untagged?

I vote for untagged.

**Comment by funderburkjim** [comment]
> While there are 297 >BR.<, 5 places have a space in between (>B. R.<).
Can the space be removed at these 5 places, to make all the items uniform?

Either way ok with me.  Each refers to Boehtlink & Roth

**Comment by funderburkjim** [comment]
Let's leave the issue open until our reworking of grassman is completed and the various potential 'todo' items of this issue are resolved.  Then we can close.
