### ISSUE TITLE
AV. links to RV.

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GRA#3]
```
(nī́la) , a., dunkelfarbig, schwarzblau, enthalten in den folgenden. 
-am AV. 15,1,7 … asya udáram lóhitām pṛṣṭhám.                  [ID=5070]
```

The `AV. 15,1,7` links to Rigveda. It should not. We have finalised AV corpora and we can use it for GRA as well, @funderburkjim  http://yoga.od.ua/doc/AVS2.html

**Comment by gasyoun** [comment]
@funderburkjim at least we should kill the AV links to RV for now.

**Comment by funderburkjim** [comment]
Thanks for reminder.

There are about 190 AV references in GRA.

I suggest we put the AVS2.html   data into the https://github.com/sanskrit-lexicon/rvlinks repository.
Agree?

@gasyoun  Please provide references for the sources -- i.e., whose translations (english, russian) are these for AV ? 

Also, please provide references for the translation sources (english, russian, german) for RV.

**Comment by funderburkjim** [comment]
Also, Do we have permission from Yoga in Odessa to use this material  (e.g., to put it into rvlinks)?
Who is responsible for the AV compilation ?

**Comment by gasyoun** [comment]
> I suggest we put the AVS2.html data into the https://github.com/sanskrit-lexicon/rvlinks repository.

Yes.

> Please provide references for the sources -- i.e., whose translations (english, russian) are these for AV ?

https://en.wikisource.org/wiki/The_Atharva_Veda/Book_1/Hymn_1 Translated by Ralph T.H. Griffith - English.
Russian:
Атхарваведа (Шаунака): В 3-х томах / Пер., вступ. ст., комм. и прил. Т. Я. Елизаренковой. (Серия «Памятники письменности Востока». Вып. CXXXV, части 1-3). М.: Вост. лит., 2005—2010. ISBN 5-02-018480-2
Т. 1. Книги I—VII. 2005. 576 стр. 1200 экз. ISBN 5-02-018479-9
Т. 2. Книги VIII—XII. 2007. 296 стр. 1200 экз. ISBN 978-5-02-018560-9
Т. 3. Книги XIII—XIX. 2010. 232 стр. 800 экз. ISBN 978-5-02-036440-0

> Who is responsible for the AV compilation ?

I.

> Do we have permission from Yoga in Odessa to use this material (e.g., to put it into rvlinks)?

No, it's my pupil, @artanat site, we can remove from it later.

**Comment by gasyoun** [comment]
`ji [Cologne record ID=3500] [Printed book page 0486]`

`[Ku. Zeitschr. 9,26]. `

`9,26` should not be linked @funderburkjim

**Comment by gasyoun** [comment]
> 1. ji, siegen [ursprünglich gvi, vgl. Cu. 639, Ku. Zeitschr. 10,289]

Anything after `Ku. Zeitschr.` should be delinked.

**Comment by funderburkjim** [comment]
1.  What is the reasoning regarding `Ku. Zeitschr.`  ?

2. You've pointed out a couple of errors in the way links to RV in GRA are currently handled.
    I agree these are good suggestions.
    I'm currently not sure how to implement these suggestions.   
    When my current focus on identifying verbs in various dictionaries runs its course,  
     I'll be more responsive in addressing these GRA issues.

**Comment by gasyoun** [comment]
> When my current focus on identifying verbs in various dictionaries runs its course,
I'll be more responsive in addressing these GRA issues.

Sure, I'm interested in verbs more than everything else.

> What is the reasoning regarding Ku. Zeitschr. ?

We can link only to RV and AV for now. Everything else in non-legal, because we do not know what the numbers stand for.

**Comment by gasyoun** [comment]
@funderburkjim closeable?

**Comment by funderburkjim** [comment]
We now have an 'avlinks' repository (https://github.com/sanskrit-lexicon/avlinks).

To develop links from Grassman's references,  we have to map Grassman's reference system
to the mandala.hymn.verse system used in avlinks.

We used [this reference](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/grapref/grapref05.html) to
develop the mapping for RV links.  

What is the AV link mapping?

**Comment by funderburkjim** [comment]
Perhaps no mapping is required?

First example, under hw 'ama' of GRA:
```
1. ({@áma@})¦, <ab>pron.</ab>, {%dieser%} (<ab>vgl.</ab> amā́, amā́t).
<div n="P1">-as AV. 14,2, 71 …‿ahám asmi.
```

and https://sanskrit-lexicon.github.io/avlinks/avhymns/av14.002.html#av14.002.071

appears to be the right link (aham asmi).

NOTE: For some reason the above url is not scrolling to verse 71

**Comment by gasyoun** [comment]
> Perhaps no mapping is required?

No idea. I will update the bibliography only, it's from Rigveda.

**Comment by funderburkjim** [comment]
There are now links for the approximately 200 AV references in Grassman.
The links go to the appropriate spots in the avlinks repository  (we are using Github to
serve these html files).

For example:  under headword 'ayopAzwi' (SLP1):
```
<L>951<pc>0098<k1>ayopAzwi<k2>a/yopAzwi
({@áyopāṣṭi@})¦, {@áyas-apāṣṭi,@} a., {%eiserne Krallen%} [<ab>vgl.</ab> apāsthá, Widerhaken, {AV. 4,6,5}] {%habend.%}
<div n="P1">-is śyenás {925,8}.
<LEND>
```
![image](https://user-images.githubusercontent.com/6393033/114235023-910cd180-994d-11eb-91f8-e2ab4077d536.png)

If we click the link we get (in a new tab):
![image](https://user-images.githubusercontent.com/6393033/114235146-c0bbd980-994d-11eb-8a05-06716bcc4b14.png)

**Comment by gasyoun** [comment]
> approximately 200 AV references in Grassman.

Thanks. I use Grassman every week when I translate the Mahabharata, so it's a gift indeed.

**Comment by funderburkjim** [comment]
## Technical notes

There were three parts:
* develop target html pages for links to individual verses of hymns of Atharva Veda.
  This done in repository https://github.com/sanskrit-lexicon/avlinks.  We use Github
  to serve the html files for  731 hymns from Atharva Veda.
* add markup to grassman digitization, gra.txt. This markup provides the data required to generate links to individual verses.
* revise the 'basciadjust.php' component of the displays.  This is where the links are generated.


## markup of GRA.
The references in grassman text are like 'AV. 1,2,3', with a few minor variations.
This would be verse 3 of hymn 2 in mandala 1.   (I'm using terminology analogous to
that for the modern references to Rg Veda).   There is no 'translation' step involved for
Grassman for AV references  (in contrast to the translation step involved for Rg Veda references in Grassman).

We add a simple markup:  '{AV. 1,2,3}'

The programs etc. involved are in [this gist](https://gist.github.com/funderburkjim/5ca81f27b2cdc79810f7c5ebd56d19ee)
* readme.txt  The specific steps
* avmarkup.py  The main program to identify the AV references and apply markup.
   The instances are identified with regular expressions.
* changes.txt  A few specific cases, where the text of gra.txt needs slight revision, and
  markup is added 'manually'
* updateByLine.py  program used to apply changes.txt

## basicadjust.php
The links and tooltips are generated from `{AV. 1,2,3}` type text of gra.xml.  The procedure is similar to the way Rg Veda links are generated for Grassman.

Reference: [basicadjust.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc/basicadjust.php)

The csl-websanlexicon version of basicadjust.php is also copied to csl-apidev repository,
so simple-search will also have the links.

**Comment by gasyoun** [comment]
> so simple-search will also have the links

Thanks, wonder if @drdhaval2785 understands how to redo the same for external Panini links.

**Comment by gasyoun** [comment]
> There are now links for the approximately 200 AV references in Grassman.

@funderburkjim let's close it.
