### ISSUE TITLE
CDSL display of AB version, part 2

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GRA#31]
@Andhrabharati   This is a continuation of #29, which was getting too long!

**Comment by Andhrabharati** [comment]
With the corrections done as discussed in the part 1 (#29), here are the global ls-items and the local ls-items
[extract_ls1_AB.txt](https://github.com/sanskrit-lexicon/GRA/files/11790906/extract_ls1_AB.txt)
[extract_ls1_local_AB.txt](https://github.com/sanskrit-lexicon/GRA/files/11790907/extract_ls1_local_AB.txt)

[I had opted to make the article type of citations as local and full book type of citations as global, as a primary distinction.]

@funderburkjim, I would like to know your opinion about this.

**Comment by Andhrabharati** [comment]
I had changed the abbr.s also in a similar manner.

**Comment by funderburkjim** [comment]
> article type of citations as local and full book type of citations as global, as a primary distinction.

Certainly fine with me.  

BTW.  In your local file:
why the greek text in 1st expansion? `n="ὕμνος. ..."`

**Comment by Andhrabharati** [comment]
It is the Article's name!

**Comment by funderburkjim** [comment]
> I had changed the abbr.s also in a similar manner.

I don't understand this comment.

**Comment by Andhrabharati** [comment]
The second criterion is dis-ambiguity.

**Comment by Andhrabharati** [comment]
> > I had changed the abbr.s also in a similar manner.
> 
> I don't understand this comment.

"Making error corrections and changing between local & global types of abbr.s"-- this is the 'similar manner' as done in the ls-items.

**Comment by Andhrabharati** [comment]
`<ls n="Πεϱνα in πέϱνημι und sanskritisch paṇ, paṇi und verwandts.— Benfeyʼs Article in Kuhnʼs Zeitschrift">`
Article name : Πεϱνα in πέϱνημι und sanskritisch paṇ, paṇi und verwandts.
Article by: Benfey
Article in the journal: Kuhnʼs Zeitschrift
`------------------------------------`
`<ls n="ὕμνος.— Aufrechtʼs Article in Kuhnʼs Zeitschrift">Aufr. in Ku.</ls>`
Article name: ὕμνος.
Article by: Aufrecht
Article in the journal: Kuhnʼs Zeitschrift
`------------------------------------`
`<ls n="Sanskritisch Sarvátâti, zendisch haurvatât, lateinisch sălût.— Benfeyʼs Article in Orient und Occident">Benf. in Or. und Occ.</ls>`
Article name: Sanskritisch Sarvátâti, zendisch haurvatât, lateinisch sălût.
Article by: Benfey
Article in the journal: Orient und Occident

Is this clear now, @funderburkjim ?

**Comment by Andhrabharati** [comment]
Not a bad idea.

But, in such a case, there would be couple of hundreds of such works have to be taken up; and I do not think its worth my time. [Sometime back, @gasyoun wanted my mind-map on few details to be put on paper (i.e. in writing); but as I doubted if he would use that at all (he mostly asks for things but forgets as soon as he gets them!), I haven't spent  even a minute on that.]

Any seriously interested person can get such details, as I do, with a little focussed lookout.

**Comment by gasyoun** [comment]
> he mostly asks for things but forgets as soon as he gets them

Not exactly, but I like your sense of humor @Andhrabharati . I do agree with you that full bibliography of Grassman is a bit early, some 50-150 more years must pass.

**Comment by Yuzki** [comment]
I would like to confirm the following (because I'm unsure if I'm catching up accurately in the discussion):

- Is it necessary to add a link to the abbreviation for GRA?
- Is it difficult to link to papers and books during that process?
- Is the @Andhrabharati 's list part of the literature that should be linked? Are there still a large number of items remaining?

By the way, regarding the "Beiträge" in #29 , the aritcle mentioned there is this one: https://www.jstor.org/stable/23458766"

**Comment by Andhrabharati** [comment]
Thanks @Yuzki , for identifying the magazine.

Now I will update both Goldschmidt's and Kuhn's citations appropriately.

**Comment by Andhrabharati** [comment]
> * Is it necessary to add a link to the abbreviation for GRA?

[Here](https://github.com/sanskrit-lexicon/GRA/issues/29#issuecomment-1584859625) is my opinion about this.

> * Is it difficult to link to papers and books during that process?

Not at all; it is such a playful work that I enjoy helping @funderburkjim in doing it.
We had some major books linked thus during last year; and probably that task would be resumed again soon

> * Is the @Andhrabharati 's list part of the literature that should be linked? Are there still a large number of items remaining?

It is just an informative list for time being; but probably, if Jim likes doing it, the linking can also be taken up.
I have identified all the items except one item, which is not that important.

**Comment by funderburkjim** [comment]
@Andhrabharati  The form in the local ls tooltips should not be `<ls n="tip">X</ls>`,  since the n-attribute for 'ls' element already has a different use (e.g. `<ls>X,1,2</ls>; <ls n="X,">3,4</ls>`.  

Let's use a different attribute name, e.g., 'ab':   `<ls ab="tip">X</ls>`.

What is your timetable for uploading next version  (graab_6) ?

**Comment by Andhrabharati** [comment]
Sorry for keeping it on hold; I was still pondering whether to put all my corrections into graab_5.

Now that you are asking for it, I shall do it today before evening (my time) and post. You can look into it when the day starts at your end.

**Comment by Andhrabharati** [comment]
> > > I had changed the abbr.s also in a similar manner.
> > 
> > 
> > I don't understand this comment.
> 
> "Making error corrections and changing between local & global types of abbr.s"-- this is the 'similar manner' as done in the ls-items.

**error correction type : 8**
```

a.:adjectiv:29 | <ab   n="adjectiv">a.</ab> | ;; change as adjektiv and mege with it
pass.:passiv:2 | <ab n="passiv">pass.</ab> | ;; change as passivisch and merge with it
Pass.:Passiv:5 | <ab n="Passiv">Pass.</ab> | ;; change as Passivisch and merge with it
f.:feminium:31 | <ab n="feminium">f.</ab> | ;; correct as femininum and merge with it
Part.:Participum:84 | <ab n="Participum">Part.</ab> | ;; correct as Participium and merge with it
Part.:Perfektum:24 | <ab n="Perfektum">Part.</ab> | ;; correct as Perf. and merge with it
d.:dort ??:1 | <ab n="dort ??">d.</ab> | ;; delete and couple with preceding "s. u." to make  "s. u. d." <ab m="siehe   unter diesen">s. u. d.</ab>
Opt.:Optativ:1 | <ab n="Optativ">Opt.</ab> | ;; merge with the other one [Optativ ] which is changed as [Optativ]
```

generic to local type (either due to disambiguation or being purely context-specific): 27
```
<ab>Ait.</ab>	<ab n="Aiton">Ait.</ab>
<ab>antreff.</ab>	<ab n="antreffen">antreff.</ab>
<ab>Bharadv.</ab>	<ab n="Bharadvāja">Bharadv.</ab>
<ab>Brahmanasp.</ab>	<ab n="Brahmanaspati">Brahmanasp.</ab>
<ab>bṛ́hasp.</ab>	<ab n="bṛ́haspátim">bṛ́hasp.</ab>
<ab>Citr.</ab>	<ab n="Citráratha">Citr.</ab>
<ab>Dsch.</ab>	<ab n="Dschamadagni">Dsch.</ab>
<ab>Gärtn.</ab>	<ab n="Gärtner">Gärtn.</ab>
<ab>Gm.</ab>	<ab n="Gmelin">Gm.</ab>
<ab>H.</ab>	<ab n="Himmel">H.</ab>
<ab>Hymn.</ab>	<ab n="Hymne">Hymn.</ab>
<ab>K.</ab>	<ab n="Karañja">K.</ab>
<ab>Lam.</ab>	<ab n="Lamarck">Lam.</ab>
<ab>Lin.</ab>	<ab n="Linnaeus">Lin.</ab>
<ab>M.</ab>	<ab n="Mātaríśva">M.</ab>
<ab>Mitr.</ab>	<ab n="Mitra">Mitr.</ab>
<ab>pp.</ab>	<ab n="perge, perge‎">pp.</ab>
<ab>Pr.</ab>	<ab n="Priyamedha">Pr.</ab>
<ab>R. Br.</ab>	<ab n="Robert Brown">R. Br.</ab>
<ab>Rich.</ab>	<ab n="Richard">Rich.</ab>
<ab>Roxb.</ab>	<ab n="Roxburghii">Roxb.</ab>
<ab>St.</ab>	<ab n="Stamm">St.</ab>
<ab>Sth.</ab>	<ab n="Sthūragūpa">Sth.</ab>
<ab>utt.</ab>	<ab n="uttama">utt.</ab>
<ab>W.</ab>	<ab n="Wetterwolke">W.</ab>
<ab>Willd.</ab>	<ab n="Willdenow">Willd.</ab>
<ab>Y.</ab>	<ab n="Yayāti">Y.</ab>
```

Generic type: 251

[Note: Few generic ones like p. (page), S. (Seite or Spalte) n. (note), N. (Note) etc. are left unmarked, which occur in the ls-numbers, which are mostly self-evident (by context).]

**Comment by Andhrabharati** [comment]
@funderburkjim 

Finally, done with my working on GRA now--
[temp_graab_6.zip](https://github.com/sanskrit-lexicon/GRA/files/11822009/temp_graab_6.zip)

If you would like to retain the 〔 〕marking for the non-RV/AV citations, as you seem to have retained the 〉 still [instead of ')'], here is my original file--
[temp_graab_6(AB).zip](https://github.com/sanskrit-lexicon/GRA/files/11822035/temp_graab_6.AB.zip)

At the last minute I had to do few more changes, and hope you could regenerate the abbr. and ls lists (again for CDSL) from this file.

Otherwise, I shall make them tomorrow and post.

**Comment by Andhrabharati** [comment]
And you may see that I have done almost all changes that were pointed in the part 1 (#29) of this issue, except the [AV tag extension after semicolon] https://github.com/sanskrit-lexicon/GRA/issues/29#issuecomment-1596485977

**Comment by Andhrabharati** [comment]
Two addl. corrections in graab_6(AB):

line 53794: `<div n="TS">-asya {913,??} tvácam {913,5}. mū́lam {10}. bálam {25}.` -> `<div n="TS">-asya tvácam {913,5}. mū́lam {10}. bálam {25}.`

line 82751: `<ls ab="?? Kuhnʼs Article in Kuhnʼs Zeitschrift">Kuhn in Zeitschr.</ls> 〔%%??,%%372—387〕`  -> `<ls ab="Die neutra auf as— Kuhnʼs Article in Kuhnʼs Zeitschrift">Kuhn in Zeitschr.</ls> 〔%%1,%%372—387〕`

**Note. The second correction is to be with { } instead of 〔〕at the end, in the graab_6.**

**Comment by Andhrabharati** [comment]
@funderburkjim 

Pl. note that there are couple of places where %%...%% is present.

I had mentioned about this earlier as my (p)adding the string to make the text "complete" in itself.
[Without this addition, the text would be 'missing' something at the resp. places.]

You may decide on how to present the same in displaying the text, keeping the text as is; or to just remove the '%%' tags at either ends and let the (p)added text 'merge' with the print text (probably as a print change).

**Comment by Andhrabharati** [comment]
Noted that the RV citations with a space inside are not "expanded" as separate links, as in case of AV citations.

Is that a deliberate decision, or a TODO task?

**Comment by Andhrabharati** [comment]
Some more corrections, with regex.` {[^0-9%@]`

line 14415: `{II. 24,11}` -> `<ls>Iliad, Homer</ls> 〔24,11〕`
line 15799: `{N. 3}` -> `〔N. 3〕`
line 25031: `{n. 4}` -> `〔n. 4〕`
line 46864: `{S. 454}` -> `〔S. 454〕`

**Comment by Andhrabharati** [comment]
One final observation, and I will "move on" from the GRA--

Except **st.** and **v. u.**, all other abbr. candidates are not tagged in the VN del & chg portion [`<L>11xxx` set]; and these two are copied as is from graab_5 into graab_6. [Originally they too were not tagged in my vn5_AB file.]

However, the integration of this portion into the main text under the chg tags has all the abbr. candidates duly tagged.

Probably to make things consistent, either these two markups are to be deleted within the `<L>11xxx` set; or every other abbr. candidate in this set should also be properly tagged.
[Also there are some hom- & ls- candidates that are not tagged thus in this set.]

**Comment by funderburkjim** [comment]
As mentioned, working  with the [] version.
* make 3 corrections [mentioned here](https://github.com/sanskrit-lexicon/GRA/issues/31#issuecomment-1601992119).
* make 4 corrections [mentioned here](https://github.com/sanskrit-lexicon/GRA/issues/31#issuecomment-1602078222).
* one additional correction, at line 48342.  `""`  -> `"`   (@Andhrabharati  please note.)

## revise one.dtd 
New 'ab' attribute 

The xml construction is now validated for the revised graab_6

**Comment by Andhrabharati** [comment]
> * one additional correction, at line 48342.  `""`  -> `"`   (@Andhrabharati  please note.)

Noted and corrected in my file.

**Comment by funderburkjim** [comment]
## re st. and v.u. in chg/del

It is appropriate to have these abbreviations in the vn material, to help a reader using the displays.
Since the other items in the chg/del section (L=11xxx) are present in the associated body 'chg' markup, we don't need to try to add these tags in the L=11xxx section.

So the inconsistency has a reason here, and can be maintained.  That's the way it seems to me.

**Comment by Andhrabharati** [comment]
Valid reason indeed! No counter-arguments!!

**Comment by funderburkjim** [comment]
## temp_graab_7
This deals with literary source markup; the work is in the *litsrc1* directory.

This starts with temp_graab_6.  There are 4 small change files [graab/.change_7a.txt](https://github.com/sanskrit-lexicon/GRA/blob/master/graab/change_7a.txt), and 7b, 7c, 7d.
temp_graab_7 is currently the same as temp_graab_7d.txt.  Only 11 lines of temp_graab_6 are changed.

The ls abbreviations (extract_ls_all.txt 143 items) were constructed as a concatenation of two files:
* extract_ls2_local.txt  derived from the `<ls ab="tip">abbrev</ls>` instances in temp_graab_7
* extract_ls1b_AB.txt    Derived from extract_ls1_AB.txt.

For display purposes, the 'local' ls tooltips were treated as global.  While the `<ls ab="tip">abbrev</ls>` instances still appear in temp_graab_7, the 'ab="tip"' portion is unused in display logic.
In a small number of cases, there were multiple tooltips for a given ls abbreviation.  To avoid this ambiguity, one or more space characters (in form of string `&#xA0;`) were added to  abbreviations
(e.g. ` Aufr. in Ku. Zeitschr.&#xA0;`)  While somewhat kludgy, this solution seems reasonable as it requires (a) minimal change to graab digitization AND (b) quite small change to display in only a few entries.

@Andhrabharati There are a small number of abbreviations in extract_ls_all.txt  with a '?' whose tooltip you may wish to review.

Anticipated next steps for me:
* review the other (non-ls) abbreviations 
* add markup to handle the RV links with spaces (e.g. {a,b. c}).

**Comment by Andhrabharati** [comment]
can you pl. post your temp_graab_7, so that I can see where the '?' places actually are and take some action?

**Comment by Andhrabharati** [comment]
have you decided not to 'correct' {11,1,2} here--
```
; <L>7676<pc>1214<k1>vayas
58890 old <div n="TS">(-āṃsi) 2〉 neben haṃsā́s <ls>AV. 8,7,24</ls>; {11,1,2}.
;
58890 new <div n="TS">(-āṃsi) 2〉 neben haṃsā́s <ls>AV. 8,7,24</ls>; <ls n="AV.">11,1,2</ls>.
```

ref. my [earlier post](https://github.com/sanskrit-lexicon/GRA/issues/29#issuecomment-1596485977)?

**Comment by Andhrabharati** [comment]
> Aufr. in Ku. Zeitschr.&#xA0;

if the volume no. of Zeitschr. is clubbed with the ls the ambiguity would have been removed, but that makes the marking inconsistent.

so this minor adjustment is alright; not an issue to break the heads on.

**Comment by Andhrabharati** [comment]
<ls>F.</ls> expansion is the same as <ls>Fi.</ls>, and
<ls>C.</ls> expansion is the same as <ls>Cu.</ls>

Either these may be separately listed, or could be changed to **Fi.** & **Cu.** resp. as at the majority cases.

**Comment by Andhrabharati** [comment]
`Co. Text	:Codice Text [Rigveda Saṃhitā Text, Chambersʼ Manuscript No. ??` is to be deleted from the ls list and to be marked as `<ab>Co.</ab> <ls>Text</ls>` at line 88020.

I could not see any issue with
`Goldschmidt in Beitr.	:?? Goldschmidtʼs Article in Beiträge` or `Goldschmidt in Beiträge	:?? Goldschmidtʼs Article in Beiträge`

For time being let `Roth	:?? (Roth, in his Nirukta ed. 1852)` remain as is with the ?? mark;  I am not too confident about the expansion, but that appears to be the most probable one.

**Comment by Andhrabharati** [comment]
And, here is the updated file--
[temp_graab_7(AB).zip](https://github.com/sanskrit-lexicon/GRA/files/11855507/temp_graab_7.AB.zip)

**Comment by funderburkjim** [comment]
## revsions to temp_graab_7

After these revisions, there remain two differences between AB's temp_graab_7(AB) version and
the cdsl temp_graab_7.txt.
```
line 71433
  7 (cdsl) Ku. in Zeitschr.&#xA0;      (since a different tooltip)
  7.AB. Ku. in Zeitschr.   

line 58890.
  7 (cdsl) <ls n="AV.">11,2,24</ls>  per AB's suggestion!
  7.AB. <ls n="AV.">11,1,2</ls>.
```

The ls abbreviations with tooltips (and counts) are in revised [litsrc1/extract_ls_all.txt](https://github.com/sanskrit-lexicon/GRA/blob/master/graab/litsrc1/extract_ls_all.txt).

**Comment by funderburkjim** [comment]
@Andhrabharati   I think work on temp_graab_7.txt can be considered done.  And I'll begin the 'next steps' mentioned [above](https://github.com/sanskrit-lexicon/GRA/issues/31#issuecomment-1605238772).

**Comment by Andhrabharati** [comment]
@funderburkjim 

Pl. change the following ls entries as--

Naigh.	:Naighaṇṭukakāṇḍa [Jâskaʼs Nirukta, sammt den Nighaṇṭavas Bd. 1— Rudolf Roth, 1852]	:21
Nir.	:Nirukta [Jâskaʼs Nirukta, sammt den Nighaṇṭavas Bd. 2— Rudolf Roth, 1852]	:12
P.	:Rig-Veda Padapāṭha	:25
Pad.	:Rig-Veda Padapāṭha	:167
Pada	:Rig-Veda Padapāṭha	:73
Pada bei Aufr.	:Rig-Veda Padapāṭha, Aufrechtʼs edition	:1
Padap.	:Rig-Veda Padapāṭha	:7
Padapāṭha	:Rig-Veda Padapāṭha	:2 

These would make the titles "complete" and more accurate!!
[I had updated/changed them in my extract_ls file(s), but did not post along with the temp_graab_6 files earlier. Sorry for the trouble.]

**Comment by funderburkjim** [comment]
ls entries changed.

**Comment by funderburkjim** [comment]
## review of abbreviations

Work in the abbrevs1 directory.
Using temp_graab_7.txt.

[extract_abbrev.txt](https://github.com/sanskrit-lexicon/GRA/blob/master/graab/abbrevs1/extract_abbrev.txt) has all the ab, pe, and lang abbreviations, both local and global.
Count summary:
```
341 global abbreviations read from graab_input_0.txt   (0 duplicates) (the current global tooltip file)
365 lines written to extract_abbrev.txt
040 ab,local
251 ab,global
003 pe,local
003 pe,global
001 lang,local
058 lang,global
```

When comparing with [this comment in issue 27](https://github.com/sanskrit-lexicon/GRA/issues/27#issuecomment-1582411044), there are differences.

At the moment, I don't see anything that needs doing here.  

Request @Andhrabharati to point me to comments that need to be implemented re abbreviations.
For instance, ⁓ [U+2053]  could be marked as an abbreviation
(per [this comment](https://github.com/sanskrit-lexicon/GRA/issues/27#issuecomment-1598751550)).

**Comment by Andhrabharati** [comment]
No other posts to see reg. the abbr.s, except the ⁓ [U+2053].

**Comment by Andhrabharati** [comment]
But, I just wish the `Zend` be made something like `Zend (Avestan)`.
[I had posted this somewhere earlier.]

**Comment by funderburkjim** [comment]
## finishing touches for abbreviations

1. change temp_graab_7 (change_7f) for `<ab>⁓</ab>`
2. Revised global abbreviation tooltip file [graab_input_2.txt](https://github.com/sanskrit-lexicon/GRA/blob/master/graab/abbrevs1/graab_input_2.txt).
  * tooltip for ⁓
  * revised tooltip 'Zend (Avestan) for abbreviation `Zend.`
  * remove unused *global* abbreviations. (29 of these) -- most (all?) of these currently marked as local abbreviations in temp_graab_7.txt.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Pl. change these two ls expansions

> Pāṇ.	:Aṣṭādhyāya— Pāṇini 	:16
> Pāṇini	:Aṣṭādhyāya— Pāṇini	:1

as
Pânini's acht Bücher grammatischer Regeln— Boethlingk, 1839-40

[And it was my mistake to name Aṣṭādhyāyī as Aṣṭādhyāya]

**Comment by Andhrabharati** [comment]
`Jenaer Literaturzeitung 1874 [Vienna University Newspaper, 1874]`
 to be changed as 
`Jenaer Literaturzeitung 1874 [Jena University Newspaper, 1874]`

[I had wrongly taken Jena = Vienna; whereas Jena is in Germany and Vienna is in Austria]

**Comment by funderburkjim** [comment]
tooltips revised per previous 2 comments.

Refer extract_ls_all.txt in above 5bffc39 commit.

**Comment by funderburkjim** [comment]
## Markup of non-standard RV links
Work done in graab/litsrc2 directory.
End result is temp_graab_8.txt 
[temp_graab_8.zip](https://github.com/sanskrit-lexicon/GRA/files/11888797/temp_graab_8.zip)

A 'Standard' RV link in gra.txt is (by definition) of the form `{x,y}` where x and y are digit sequences.
A 'non-standard' RV link is of the form (in temp_graab_7) of form `{Z}`, where 'Z' starts with a digit, but `{Z}` is not Standard.
temp_graab_7 was found to have 113486 standard rvlinks and 4176 *distinct* non-standard rvlinks.

After changes (to 2545 of the 89186 lines), temp_graab_8 has 124901 standard rvlinks and 0 non-standard links.

A sample change shows how  1 non-standard link becomes 2 standard links
* `{1,2. 5} -> {1,2}. _{1,5}` 
* The second (implied) link is coded as `_{1,5}`  
* The `_{` markup indicates that this is an inferred link (not present in print).  We can remove this '_' in displays if we want to.  But it seems useful to be able to identify those 'inferred' links in the gra.txt file, hence the presence of the '_{' therein.

In the 'reform_1.txt' file, all similar examples are coded as ',A'.  Several similar kinds of  systematic changes were identified with B,C,D in reform_1.

This leaves 122 (distinct) non-standard rvlinks, identified by `,?` in reform_1.txt.
These were corrected manually, and can be seen in litsrc2/change_8a_8b.txt.
For example, under aMsatrakoSa, {8} was changed to _{927,8}, since there was a preceding {927,7}.

Another type is seen under agnidagDa, where {929} was changed to _{929,1}.  Here the reference 929 is to a particular hymn.  I decided to make the inferred link map to the first verse of this hymn (by adding `,1` to the link). -- thus in the display, a user will be able to get to that hymn.
