### ISSUE TITLE
Replacing grahwextra with Lbody

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GRA#34]
At https://github.com/sanskrit-lexicon/MWS/issues/176, the 'alternates' of MW were recoded using Lbody entries.  This was inspired by the handling of alternates in Grassman ([see althws for gra in csl-orig](https://github.com/sanskrit-lexicon/csl-orig/tree/master/v02/gra/althws).

In this issue, I replace the althws approach with the Lbody approach.

This starts out as an experiment.

**Comment by funderburkjim** [comment]
https://sanskrit-lexicon.uni-koeln.de/work/gratest_lbody/web/webtc1/index.php provides a test version of the standard Grassman displays.  These are generated by the `{{Lbody=n}}` entries of revised gra.txt.

The only difference in displays that I've noticed is that the new version does not have the 'X is an alternate of Y' message.  

Previous version:

<img width="738" alt="image" src="https://github.com/user-attachments/assets/c8a34ebb-8860-4148-8fac-20d4317abb79">


New test version:

<img width="725" alt="image" src="https://github.com/user-attachments/assets/9d1a7b8e-0ea5-407c-81d5-20f837a8e2a7">

**Comment by funderburkjim** [comment]
I think the new version is ready to install as the production version of GRA at cdsl.

Request others to use the new test displays some, and provide feedback.

The work for this version is in the [issues/issue34](https://github.com/sanskrit-lexicon/GRA/tree/master/issues/issue34) directory of this repo

**Comment by Andhrabharati** [comment]
> The work for this version is in the [issues/issue34](https://github.com/sanskrit-lexicon/GRA/tree/master/issues/issue34) directory of this repo

**althws** folder appears (**by mistake ?**) inside **graab** folder as well, in addition to the **issues/issue34** folder!!

> The only difference in displays that I've noticed is that the new version does not have the 'X is an alternate of Y' message.

This reminds me of my earlier post about this "wrong" message" being displayed!!

**Comment by funderburkjim** [comment]
## revised version installed.

Now gra and mw use the {{Lbody=N}} markup in xxx.txt.
The xxx_hwextra.txt is unused.
`<h>` field is used for metaline homonyms.

## Further conversions

11 dictionaries still use the xxx_hwextra method for alternates:
```
 129153 Sep 28  2019 acc/acc_hwextra.txt
  44300 Sep 18  2021 ap90/ap90_hwextra.txt
     53 Sep 17  2021 ben/ben_hwextra.txt
     65 Jan 13  2020 bur/bur_hwextra.txt
     54 Sep 28  2019 cae/cae_hwextra.txt
 453540 Oct 11  2022 lrv/lrv_hwextra.txt
1529080 Mar 25  2024 pw/pw_hwextra.txt
 309788 Dec 18  2023 pwkvn/pwkvn_hwextra.txt
   1150 Dec 15  2023 shs/shs_hwextra.txt
  22736 Feb  2  2020 skd/skd_hwextra.txt
 116677 Jul 10  2020 vcp/vcp_hwextra.txt
```

I intend to convert all these to the {{Lbody=N}} markup form.

Closing this issue.

**Comment by funderburkjim** [comment]
> I intend to convert all these to the {{Lbody=N}} markup form

This now completed.
