### ISSUE TITLE
Prǎpositionen -> Präpositionen

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GRA#6]
`a [Cologne record ID=1] [Printed book page 0001]`
`1. (a) . Deutestamm der 3. Person, siehe unter idám. Mit ihm zusammengesetzt sind á-tas, á-tra, a-dyá und wahrscheinlich alle Prǎpositionen und Partikeln`

`Prǎpositionen -> Präpositionen` wonder if `ǎ` is the only one in GRA.

![ae](https://user-images.githubusercontent.com/80761/76152857-9148f680-60d5-11ea-9799-45c739939862.PNG)

**Comment by funderburkjim** [comment]
Found 3 other cases:

## 1) 10718, hU  `vǎm ` -> `vām`

![image](https://user-images.githubusercontent.com/6393033/76266627-76de5c80-623e-11ea-99ee-fb485c42e58e.png)


## 2) ac, L=144.  no change
`-āmi. pári 945,5 matím táṣṭǎ‿iva vandhúram.`

![image](https://user-images.githubusercontent.com/6393033/76266730-cae94100-623e-11ea-9d96-63448f09efd7.png)



## 3) has, L=10620  no change
Not sure of diacritic mark here.

`Verbale {@hǎs@}`

![image](https://user-images.githubusercontent.com/6393033/76266881-51058780-623f-11ea-9451-854153d57311.png)

**Comment by drdhaval2785** [comment]
Working as expected.

**Comment by Andhrabharati** [comment]
> 2) ac, L=144. no change

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/da0aa23e-f883-49fe-864c-d3edfcbe19e9)


> 3) has, L=10620 no change

![image](https://github.com/sanskrit-lexicon/GRA/assets/75209130/2119635e-0c76-41bb-81c1-79de4943e626)

I've changed these two accordingly, in my file.
