### ISSUE TITLE
Grassman Abbreviations Without Tooltips

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GRA#8]
`-ema [Opt.]` - no abbreviation in GRA for Optativ.

**Comment by gasyoun** [comment]
And case endings left out, @funderburkjim 
Should I make a list of what's left out?

mit dem `Vok. `

```
vāstu [Printed book page 1264]vā́stu, n. [von 3. vas], Wohnstätte, Haus und Hof, Haus; vgl. su-vā́stu.-u 645,5 (ádhi kṣitas).-os [G.] mit dem Vok. pate verbunden … pate 570,1—3; 571,1; 637,14.-os [G.] pátim 395,8; 887,7.-ūni vām 154,6.                  [ID=7945]

```
![oss](https://user-images.githubusercontent.com/80761/108477100-da249b80-72a3-11eb-9107-e8a508b2e8d3.JPG)

**Comment by funderburkjim** [comment]
Currently, we have no abbreviation markup for GRA.

In order to add such markup,  a list of words that should be marked as abbreviations
would be needed.  So, yes - you should make a list.
Be sure to include the periods  (`vgl.`)  in such a list.
Also, provide the 'abbreviation expansion'.

The '3. vas'  case is not an abbreviation.  The '3.' is a homonym number.  It could
be marked as `<hom>3.</hom> vas`  (which is the form of our markup for
MW homonym numbers.)

**Comment by gasyoun** [comment]
> <hom>3.</hom> vas (which is the form of our markup for MW homonym numbers.)

Can it be done with a Regex?

> In order to add such markup, a list of words that should be marked as abbreviations would be needed. So, yes - you should make a list.

Please give the PWG sample, I'll base it on that, the way it works on site right now.

**Comment by funderburkjim** [comment]
The pwg abbreviation expansion file is [pwgab_input.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/pwg/pywork/pwgab/pwgab_input.txt)

Make your file follow this format for GRA abbreviations.

Put your file of Grassman abbreviations as a comment in this issue, and I'll do the installation.

**Comment by funderburkjim** [comment]
Re the markup of homonyms:

Yes, the markup can MOSTLY be done with regexes.  We will have to worry about 'false positives' (i.e., marking as homonym some number that is not a homonym).

When we've done the abbreviation task,  we can tackle the homonym markup.

**Comment by gasyoun** [comment]
> Make your file follow this format for GRA abbreviations.

@funderburkjim counted all, most fitted, some deleted, some added

Abl.	<id>Abl.</id> <disp>Ablativ - ablative (case)</disp>		87
Absol.	<id>Absol.</id> <disp>Absolutiv - absolutive (case)</disp>	28
Acc.	<id>Acc.</id> <disp>Accusativ - accusative (case)</disp>	230
act.	<id>act.</id> <disp>Activ - active </disp>			37
Adv.	<id>Adv.</id> <disp>Adverb - adverb</disp>			94
adv.	<id>adv.</id> <disp>adverbial? - adverbial</disp>		41
Aor.	<id>Aor.</id> <disp>Aorist - aorist</disp>			368
Bed.	<id>Bed.</id> <disp>Bedeutungen(?) - meanings</disp>		70
Caus.	<id>Caus.</id> <disp>Causativ - causative</disp>		645
Conj.	<id>Conj.</id> <disp>Conjunctiv? - subjunctive (mood)</disp>	98
dass.	<id>dass.</id> <disp>dasselbe - the same</disp>			439
Dat.	<id>Dat.</id> <disp>Dativ - dative (case)</disp>		158
Denom.	<id>Denom.</id> <disp>Denominativ? - denominative</disp>	5
Desid.	<id>Desid.</id> <disp>Desiderativ - desiderative</disp>		125
du.	<id>du.</id> <disp>Dual - dual </disp>				1030
Gen.	<id>Gen.</id> <disp>Genitiv - genitive (case)</disp>		661
Inf.	<id>Inf.</id> <disp>Infinitiv - infinitive</disp>		217
Infin.	<id>Infin.</id> <disp>Infinitiv - infinitive</disp>		35
Instr.	<id>Instr.</id> <disp>Instrumental - instrumental (case)</disp>	156
Intens.	<id>Intens.</id> <disp>Intensiv - intensive</disp>		213
Loc.	<id>Loc.</id> <disp>Locativ - locative case</disp>		116
L.	<id>L.</id> <disp>Locativ - locative case</disp>		142
Med.	<id>Med.</id> <disp>Medium - ātmanepada</disp>			40
med.	<id>med.</id> <disp>Medium - ātmanepada</disp>			182
Metr.	<id>Metr.</id> <disp>Meter - metre require</disp>		1
N.	<id>N.</id> <disp>Name - name</disp>				22
Nom.	<id>Nom.</id> <disp>Nominativ - noun</disp>			51
Partic.	<id>Partic.</id> <disp>Participium - participle</disp>		10
Part.	<id>Part.</id> <disp>Participium - participle</disp>		1402
Pass.	<id>Pass.</id> <disp>Passiv - passive</disp>			97
Patron.	<id>Patron.</id> <disp>Patronym - patronym</disp>		1
Pl.	<id>Pl.</id> <disp>Plural - plural</disp>			2
pl.	<id>Pl.</id> <disp>Plural - plural</disp>			640
Präp.	<id>Präp.</id> <disp>Präposition - preposition</disp>		14
Sing.	<id>Sing.</id> <disp>Singular - singular</disp>			28
Subst.	<id>Subst.</id> <disp>Substantiv - noun</disp>			64
subst.	<id>subst.</id> <disp>Substantiv - noun</disp>			18
Vgl.	<id>Vgl.</id> <disp>Vergleiche - compare</disp>			240
vgl.	<id>vgl.</id> <disp>Vergleiche - compare</disp>			1430
Voc.	<id>Voc.</id> <disp>Vocativ - vocative (case)</disp>		39
Adj.	<id>Adj.</id> <disp>Adjectiv - adjective</disp>			154
adj.	<id>adj.</id> <disp>adjectivisch - adjective</disp>		4
f.	<id>f.</id> <disp>femininum - feminine</disp>			2393
m.	<id>m.</id> <disp>masculinum - masculine</disp>			3012
n.	<id>n.</id> <disp>neutrum - neuter</disp>			1584

pron.	<id>pron.</id> <disp>Pronomen - pronoun</disp>			22
me.	<id>me.</id> <disp>Medium - ātmanepada</disp>			579
st.	<id>st.</id> <disp>stadt - instead of</disp>			1
urspr.	<id>urspr.</id> <disp>ursprünglich - originally</disp>		22
neutr.	<id>neutr.</id> <disp>neutrum - neuter</disp>			41
u. s. w.<id>u. s. w.</id> <disp>neutrum - neuter</disp>			740
v.	<id>v.</id> <disp>von - from</disp>				108
p.	<id>p.</id> <disp>proprium - Nomen propium</disp>		815
u.	<id>u.</id> <disp>und - and</disp>				97
ähnl.	<id>ähnl.</id> <disp>ähnlich - similar</disp>			6
od.	<id>od.</id> <disp>oder - or</disp>				34
s.	<id>s.</id> <disp>sehe - see</disp>				1318
Iv.	<id>Iv.</id> <disp>?</disp>					108
Impv.	<id>Impv.</id> <disp>Imperativ - imperative</disp>		68
Praes. 	<id>Praes.</id> <disp>Praesens - present</disp>			7
Ind.	<id>Ind.</id> <disp>Indicativ - indicative</disp>		28
Indic.	<id>Indic.</id> <disp>Indicativ - indicative</disp>		5
pag.	<id>pag.</id> <disp>pagination - page</disp>			1
Cu.	<id>Cu.</id> <disp>Cu.? - ?</disp>				355
C.	<id>C.</id> <disp>Causativ - causative</disp>			17
lat.	<id>lat.</id> <disp>lateinisch - latin</disp>			101
goth.	<id>goth.</id> <disp>gothisch - gothic</disp>			27
osc.

**Comment by funderburkjim** [comment]
@gasyoun  The last line in your table above is 'osc.' ---  not complete.

**Comment by gasyoun** [comment]
> above is 'osc.' --- not complete.

And let it remain such - incomplete. Better incomplete with tooltips, than complete unmarked ))

**Comment by funderburkjim** [comment]
Here are a few other abbreviations -- @gasyoun  Do you know what the tooltip should be?
```
Impf.	<id>Impf.</id> <disp>? - imperfect</disp>	234
Imperf.	<id>Imperf.</id> <disp>? - imperfect</disp>	136

Could also add
'Augm.' 6
'o.' 134  (122 occur as 's. o.')
```

**Comment by funderburkjim** [comment]
@gasyoun   Have a local version with abbreviations.

There are still several  with missing or incomplete tooltips.
Please revise these if possible.

It is easier to leave the 'missing or incomplete' cases still marked as abbreviations (but with incomplete tooltips).

Note on 'N.':  The tooltip is currently 'Name -name'  (There is example in 'pati')
I think it can also be 'nominative case'  (not sure of German here).

**Comment by funderburkjim** [comment]
After your revisions, I will complete the installation steps for Grassman abbreviations.

**Comment by gasyoun** [comment]
> It is easier to leave the 'missing or incomplete' cases still marked as abbreviations (but with incomplete tooltips).

Agree.

Impf.	<id>Impf.</id> <disp>Imperfekt - imperfect</disp>	234
Imperf.	<id>Imperf.</id> <disp>Imperfekt - imperfect</disp>	136

> 'o.' 134  (122 occur as 's. o.')
'o.' and 's. o.' are not equal.

Augm.<id>Augm.</id> <disp>Augment - augment</disp>
o.<id>o.</id> <disp>ohne - without</disp> as in `o. Augm.` = `ohne Augm.`

> Note on 'N.': The tooltip is currently 'Name -name' (There is example in 'pati')
>I think it can also be 'nominative case' (not sure of German here).

Nominativ.

**Comment by funderburkjim** [comment]
GRA now updated for abbreviations.  

The marked abbreviations are in [graab_input.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/gra/pywork/graab/graab_input.txt).  This is mostly the same as the list shown above, but with a few additions.  These abbreviations now have tooltips in the displays.

**Comment by funderburkjim** [comment]
## Technical notes

There are two related parts of the software and data that are enhanced:
* adding markup to the digitization gra.txt
* adding 'graab.sqlite' to be used by displays

graab_input.txt is the common point between these two parts.

## adding markup
See [this gist](https://gist.github.com/funderburkjim/3a475944a1374164d5fad1724661b728) for the files and programs involved:
* readme.txt  Describes the steps to add `<ab>x</ab>` markup to gra.txt
* abbrev_input.txt   Local copy of graab_input.txt.  We add markup to these abbreviations
* abmarkup.py program that adds the markup.
* abmarkup_log.txt  shows counts of lines changed due to various abbreviation markup.

It is important and a bit tricky to add markup only within certain textual contexts.
The output of abmarkup_log.txt provides a bit of insight into this 'context'. Consider
`A. 2702: 1 199 2501 1` in the log file.
We have that 'A.' is an abbreviation.  It occurs (and is marked) in 2702 lines. There are
four contexts:
* A. occurs at beginning of a line of gra.txt.  1 instance
* A. occurs preceded by a space:  occurs in 199 lines
* A. occurs preceded by a left square bracket (`[`):  occurs in 2501 lines
* A. occurs preceded by a left parenthesis (`(`): occurs in 1 line.

It is conceivable that we will discover other contexts of the 'A.' abbreviation.

There are a few cases where additional special logic is required to avoid adding 
inappropriate markup.  For instance, `I.` is an abbreviation for instrumental case.
However,  `I.`  can also be a Roman numeral, which occurs a couple of hundred times
in `Stamm I.`; special logic is required so that the Roman numeral form of 'I.' is not 
marked as an abbreviation.

There are a couple of other 'special logic' sections in abmarkup.py.  It is possible that
there are some false abbreviation markups that abmarkup.py does not yet handle.

**Comment by funderburkjim** [comment]
## tooltips and displays

In order for the abbreviation markup to make its way into display tooltips, several
adjustments are required in the csl-pywork repository.

## graab directory
The [graab](https://github.com/sanskrit-lexicon/csl-pywork/tree/master/v02/distinctfiles/gra/pywork/graab) directory  is modeled after the [pwab]https://github.com/sanskrit-lexicon/csl-pywork/tree/master/v02/distinctfiles/pw/pywork/pwab) directory.

It contains the 'graab_input.txt' file of abbreviations and tooltips and supporting software
that converts graab_input.txt into a sqlite file 'graab.sqlite' and copies that to the
gra/web/sqlite/ directory used by displays.

## inventory.txt
[inventory.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/inventory.txt)
 contains the files required for constructing the displays for the various dictionaries.  
We must add the files in graab directory so the tooltips for gra displays will be available. This is done in this portion of the inventory file:
```
; --------------------------------------------------------------
; -- abbreviations
; --------------------------------------------------------------
;   Currently, treat as distinct files
;   Later, try to get all abbreviations to be the same,
;   so templates can be used.
;   also xxx to redo_postxml.sh for abbreviations
stc bur cae mw pw pwg lan gra:pywork/${dictlo}ab/${dictlo}ab.sql:CD
stc bur cae mw pw pwg lan gra:pywork/${dictlo}ab/${dictlo}ab_input.txt:CD
stc bur cae mw pw pwg lan gra:pywork/${dictlo}ab/readme.txt:CD
stc bur cae mw pw pwg lan gra:pywork/${dictlo}ab/redo.sh:CD
stc bur cae mw pw pwg lan gra:pywork/${dictlo}ab/redo_${dictlo}ab.sh:CD
```

## redo_postxml.sh
[redo_postxml.sh](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/makotemplates/pywork/redo_postxml.sh)  takes care of running
the graab scripts when constructing the web directory used by displays for a dictionary.
We must add 'gra' to the list of dictionaries that need their abbreviation scripts run:
```
# For applicable dictionaries, update other web/sqlite databases
# abbreviations
%if dictlo in ['stc','bur','cae','mw','pw','pwg','lan','gra']:
 cd ${dictlo}ab
 sh redo.sh
 cd ../ # back to pywork
%endif
```

**Comment by funderburkjim** [comment]
The above technical notes provide a good model for how to add abbreviation tooltips to the display of a Cologne dictionary.

By far the hardest part is:
* identifying the text in a dictionary that needs to be marked as an abbreviation and then constructing the 'abbrev_input.txt' file of tooltips for those identified texts, AND
* writing a version of 'abmarkup.py' that safely adds markup to those texts  (while avoiding
  as much as possible the introduction of false-positive markup.

**Comment by gasyoun** [comment]
> 'special logic' sections in abmarkup.py

So it's GRA specific. 

> stc bur cae mw pw pwg lan gra

So these have tooltips implemented. 

> We must add 'gra' to the list of dictionaries that need their abbreviation scripts run

In what script? Or just run `redo_postxml.sh`?

> adds markup to those texts (while avoiding as much as possible the introduction of false-positive markup

Right, so it's a regex party that can take a few hours.

Thanks for documenting. @drdhaval2785 can I ask you to do a test with SKD and add a few abbreviations so there is at least one person other than Jim that know how it actually works?

**Comment by funderburkjim** [comment]
> Or just run redo_postxml.sh?


redo_postxml.sh generates the abbreviations at display generation time, but just
for those dictionaries listed (see redo_postxml.sh note above where 'gra' was
added to the list of dictionaries with abbreviations).

**Comment by Andhrabharati** [comment]
**osc.** is not a regular abbr., but is the language **Oscan**

**Comment by Andhrabharati** [comment]
And just the info, my present GRA working has almost 290 abbr. entries marked.
