### ISSUE TITLE
Mark nonexisting words *gva, *cākṣa, *ghrabh

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GRA#9]
The only language that has markup in GRA is Greek and everything is perfect with it now. But other languages are not marked, like `altlat.` = `Old Latin` in `ásṛj selbst ist aus *asar, gr. <lang n="greek">ἔαρ</lang> altlat. assir, assar-` or `*cākṣa und dies aus *cākya entstanden, vgl. gr. <lang n="greek">κίσσα, κίττα</lang> für <lang n="greek">*κικjα</lang> (wie <lang n="greek">ἥσσων, ἥττων</lang> für <lang n="greek">ἡκjων</lang>), und althochd. hehara, heigero (angels. higere), der <i>Heher,</i> der <i>blaue Holzheher</i> (Coracias indica).`

Another big group is nonexisting words, restored, bet never attested forms with * before, like `*kal` `*kṣu, deren Erweiterungen kṣud und kṣubh`, `von *gabh=jabh`, `*ghrabh`, `von gā, kommen, ursprünglich *gva`, `*gvi (jvi)`, `ursprünglich * sakv, sacante = *sakvante`.

In `* sakv` no need for the space after *.
In `nachweisbares Subst.*skṛdhas` space needed before *.

Whitelist: `<F>*)Anm.` that is a different case.

**Comment by Andhrabharati** [comment]
> The only language that has markup in GRA is Greek and everything is perfect with it now. But other languages are not marked, like `altlat.` = `Old Latin`

My current revision of GRA has all languages (in all variant spellings/forms) properly tagged.
[GRA lang tags.txt](https://github.com/sanskrit-lexicon/GRA/files/11521745/GRA.lang.tags.txt)

[I've added many such tags additionally.].

**Comment by Andhrabharati** [comment]
Sure, I can @funderburkjim .

But I presume, the tooltip should contain both German and English; what do you say?

I can try making the German tip(s), but feel someone more acquainted should be counter-checking the same; probably @maltenth could be requested to do so.

**Comment by Andhrabharati** [comment]
Anyway, let's start with the English tooltips first, which is a fairly simpler task to complete.

Give me a day, to finish my present GRA task.

**Comment by funderburkjim** [comment]
Fine to use English tooltips for the 'lang' abbreviations -- I suspect that most modern German users are also proficient in English.

For the 'normal' German abbreviations (e.g. Vgl. ), it will be good to consult @maltenth to provide both German and English tooltips.

**Just as an aside**: when considering the language(s) in which to present tooltips in Grassman, we may be touching upon the more general subject of 'website localization'.  This is a large topic and one which the CDSL website has almost completely ignored.  Some future maintainer of CDSL might decide to add localization features. For instance, a user might prefer tooltips to be in English, German, Hindi, Russian, etc.  And also button names, help file texts, and other UI elements would be localized.  Not a trivial task.

**Comment by Andhrabharati** [comment]
I could not _decipher_ one entry **ndd.**, in the updated file--
[GRA lang tags with expansion.txt](https://github.com/sanskrit-lexicon/GRA/files/11534620/GRA.lang.tags.with.expansion.txt)

**Comment by Andhrabharati** [comment]
On a second thought, could **ndd.** be Niederdeutsch (Low German)?

**Comment by funderburkjim** [comment]
I've requested @maltenth to review ndd. and also the 'GRA lang tags with expansion.txt'.

**Comment by Andhrabharati** [comment]
One correction--
`<lang>angels.</lang>	English` should've been
`<lang>angels.</lang>	Anglo-Saxon`

**Comment by Andhrabharati** [comment]
There is another entry, which was wrongly marked as ab tag earlier--
`<lang>skt.</lang>	Sanskrit`

**Comment by Andhrabharati** [comment]
Good to know that I guessed both of them correctly!

**Comment by Andhrabharati** [comment]
is this issue closable now, @funderburkjim ?

**Comment by funderburkjim** [comment]
yes, I guess so.
